// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/data_format/features.proto

#include "scann/data_format/features.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "absl/strings/internal/string_constant.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace research_scann {

inline constexpr GenericFeatureVector_FixedPointMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        squared_l2_norm_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenericFeatureVector_FixedPointMetadata::GenericFeatureVector_FixedPointMetadata(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenericFeatureVector_FixedPointMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenericFeatureVector_FixedPointMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenericFeatureVector_FixedPointMetadataDefaultTypeInternal() {}
  union {
    GenericFeatureVector_FixedPointMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenericFeatureVector_FixedPointMetadataDefaultTypeInternal _GenericFeatureVector_FixedPointMetadata_default_instance_;

inline constexpr GenericFeatureVector_Crowding::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        crowding_attribute_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR GenericFeatureVector_Crowding::GenericFeatureVector_Crowding(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenericFeatureVector_CrowdingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenericFeatureVector_CrowdingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenericFeatureVector_CrowdingDefaultTypeInternal() {}
  union {
    GenericFeatureVector_Crowding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenericFeatureVector_CrowdingDefaultTypeInternal _GenericFeatureVector_Crowding_default_instance_;

inline constexpr GenericFeatureVector_RestrictTokens::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        token_membership_{},
        _token_membership_cached_byte_size_{0},
        whitelist_token_{},
        _whitelist_token_cached_byte_size_{0},
        blacklist_token_{},
        _blacklist_token_cached_byte_size_{0},
        v3_compatible_namespace_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        v3_{nullptr},
        v2_restricts_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR GenericFeatureVector_RestrictTokens::GenericFeatureVector_RestrictTokens(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenericFeatureVector_RestrictTokensDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenericFeatureVector_RestrictTokensDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenericFeatureVector_RestrictTokensDefaultTypeInternal() {}
  union {
    GenericFeatureVector_RestrictTokens _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenericFeatureVector_RestrictTokensDefaultTypeInternal _GenericFeatureVector_RestrictTokens_default_instance_;

inline constexpr GenericFeatureVector::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        feature_value_int64_{},
        _feature_value_int64_cached_byte_size_{0},
        feature_value_float_{},
        feature_value_double_{},
        feature_index_{},
        _feature_index_cached_byte_size_{0},
        tokens_{},
        _tokens_cached_byte_size_{0},
        data_id_str_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        feature_value_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        class_label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userinfo_{},
        restrict_tokens_{nullptr},
        crowding_{nullptr},
        fixed_point_metadata_{nullptr},
        expiration_timestamp_{nullptr},
        feature_type_{static_cast< ::research_scann::GenericFeatureVector_FeatureType >(0)},
        weight_{0},
        norm_type_{static_cast< ::research_scann::GenericFeatureVector_FeatureNorm >(0)},
        feature_dim_{::uint64_t{18446744073709551615u}} {}

template <typename>
PROTOBUF_CONSTEXPR GenericFeatureVector::GenericFeatureVector(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenericFeatureVectorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenericFeatureVectorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenericFeatureVectorDefaultTypeInternal() {}
  union {
    GenericFeatureVector _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenericFeatureVectorDefaultTypeInternal _GenericFeatureVector_default_instance_;
}  // namespace research_scann
static ::_pb::Metadata file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto = nullptr;
const ::uint32_t TableStruct_scann_2fdata_5fformat_2ffeatures_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_Crowding, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_Crowding, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_Crowding, _impl_.crowding_attribute_),
    0,
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.v3_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.token_membership_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.whitelist_token_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.blacklist_token_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.v3_compatible_namespace_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_.v2_restricts_),
    1,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_FixedPointMetadata, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_FixedPointMetadata, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_FixedPointMetadata, _impl_.squared_l2_norm_),
    0,
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _internal_metadata_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_._extensions_),
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_type_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.data_id_str_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_value_float_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_value_double_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_value_int64_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_value_string_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_index_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.norm_type_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.class_label_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.crowding_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.restrict_tokens_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.fixed_point_metadata_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.userinfo_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.expiration_timestamp_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.feature_dim_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.weight_),
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector, _impl_.tokens_),
    8,
    0,
    ~0u,
    ~0u,
    ~0u,
    1,
    ~0u,
    10,
    2,
    5,
    4,
    6,
    3,
    7,
    11,
    9,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::research_scann::GenericFeatureVector_Crowding)},
        {10, 27, -1, sizeof(::research_scann::GenericFeatureVector_RestrictTokens)},
        {35, 44, -1, sizeof(::research_scann::GenericFeatureVector_FixedPointMetadata)},
        {45, 70, -1, sizeof(::research_scann::GenericFeatureVector)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::research_scann::_GenericFeatureVector_Crowding_default_instance_._instance,
    &::research_scann::_GenericFeatureVector_RestrictTokens_default_instance_._instance,
    &::research_scann::_GenericFeatureVector_FixedPointMetadata_default_instance_._instance,
    &::research_scann::_GenericFeatureVector_default_instance_._instance,
};
const char descriptor_table_protodef_scann_2fdata_5fformat_2ffeatures_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n scann/data_format/features.proto\022\016rese"
    "arch_scann\032\037google/protobuf/timestamp.pr"
    "oto\032 scann/coscann/v2_restricts.proto\032\033s"
    "cann/proto/restricts.proto\"\217\013\n\024GenericFe"
    "atureVector\022F\n\014feature_type\030\001 \002(\01620.rese"
    "arch_scann.GenericFeatureVector.FeatureT"
    "ype\022\023\n\013data_id_str\030\002 \001(\014\022\037\n\023feature_valu"
    "e_float\030\004 \003(\002B\002\020\001\022 \n\024feature_value_doubl"
    "e\030\005 \003(\001B\002\020\001\022\037\n\023feature_value_int64\030\003 \003(\003"
    "B\002\020\001\022\034\n\024feature_value_string\030\r \001(\014\022\031\n\rfe"
    "ature_index\030\006 \003(\004B\002\020\001\022I\n\tnorm_type\030\t \001(\016"
    "20.research_scann.GenericFeatureVector.F"
    "eatureNorm:\004NONE\022\023\n\013class_label\030\020 \001(\t\022\?\n"
    "\010crowding\030\022 \001(\0132-.research_scann.Generic"
    "FeatureVector.Crowding\022L\n\017restrict_token"
    "s\030\017 \001(\01323.research_scann.GenericFeatureV"
    "ector.RestrictTokens\022U\n\024fixed_point_meta"
    "data\030\023 \001(\01327.research_scann.GenericFeatu"
    "reVector.FixedPointMetadata\022\024\n\010userinfo\030"
    "\021 \001(\014B\002\010\001\0228\n\024expiration_timestamp\030\024 \001(\0132"
    "\032.google.protobuf.Timestamp\022-\n\013feature_d"
    "im\030\n \001(\004:\02418446744073709551615B\002\030\001\022\022\n\006we"
    "ight\030\010 \001(\002B\002\030\001\022\024\n\006tokens\030\016 \003(\005B\004\020\001\030\001\032&\n\010"
    "Crowding\022\032\n\022crowding_attribute\030\001 \001(\003\032\212\003\n"
    "\016RestrictTokens\022&\n\002v3\030\007 \001(\0132\032.research_s"
    "cann.V3Restrict\022\034\n\020token_membership\030\001 \003("
    "\003B\002\020\001\022\033\n\017whitelist_token\030\002 \003(\003B\002\020\001\022\033\n\017bl"
    "acklist_token\030\003 \003(\003B\002\020\001\022I\n\017easy_definiti"
    "on\030\006 \001(\0132..research_scann.coscann.EasyRe"
    "strictDefinitionH\000\022:\n\006tokens\030\005 \001(\0132(.res"
    "earch_scann.coscann.RestrictTokensV2H\000\022@"
    "\n\ndefinition\030\004 \001(\0132*.research_scann.cosc"
    "ann.RestrictDefinitionH\000\022\037\n\027v3_compatibl"
    "e_namespace\030\010 \001(\tB\016\n\014v2_restricts\032-\n\022Fix"
    "edPointMetadata\022\027\n\017squared_l2_norm\030\001 \001(\002"
    "\"T\n\013FeatureType\022\013\n\007UNKNOWN\020\000\022\t\n\005INT64\020\001\022"
    "\t\n\005FLOAT\020\002\022\n\n\006DOUBLE\020\003\022\n\n\006STRING\020\004\022\n\n\006BI"
    "NARY\020\005\"I\n\013FeatureNorm\022\010\n\004NONE\020\000\022\016\n\nUNITL"
    "2NORM\020\001\022\020\n\014STDGAUSSNORM\020\002\022\016\n\nUNITL1NORM\020"
    "\003*\t\010\350\007\020\200\200\200\200\002B\003\370\001\001"
};
static const ::_pbi::DescriptorTable* const descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
        &::descriptor_table_scann_2fcoscann_2fv2_5frestricts_2eproto,
        &::descriptor_table_scann_2fproto_2frestricts_2eproto,
};
static ::absl::once_flag descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto = {
    false,
    false,
    1577,
    descriptor_table_protodef_scann_2fdata_5fformat_2ffeatures_2eproto,
    "scann/data_format/features.proto",
    &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once,
    descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_deps,
    3,
    4,
    schemas,
    file_default_instances,
    TableStruct_scann_2fdata_5fformat_2ffeatures_2eproto::offsets,
    file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto,
    file_level_enum_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto,
    file_level_service_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_getter() {
  return &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_scann_2fdata_5fformat_2ffeatures_2eproto(&descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto);
namespace research_scann {
const ::google::protobuf::EnumDescriptor* GenericFeatureVector_FeatureType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto);
  return file_level_enum_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GenericFeatureVector_FeatureType_internal_data_[] = {
    393216u, 0u, };
bool GenericFeatureVector_FeatureType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr GenericFeatureVector_FeatureType GenericFeatureVector::UNKNOWN;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::INT64;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::FLOAT;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::DOUBLE;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::STRING;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::BINARY;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::FeatureType_MIN;
constexpr GenericFeatureVector_FeatureType GenericFeatureVector::FeatureType_MAX;
constexpr int GenericFeatureVector::FeatureType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* GenericFeatureVector_FeatureNorm_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto);
  return file_level_enum_descriptors_scann_2fdata_5fformat_2ffeatures_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t GenericFeatureVector_FeatureNorm_internal_data_[] = {
    262144u, 0u, };
bool GenericFeatureVector_FeatureNorm_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::NONE;
constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::UNITL2NORM;
constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::STDGAUSSNORM;
constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::UNITL1NORM;
constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::FeatureNorm_MIN;
constexpr GenericFeatureVector_FeatureNorm GenericFeatureVector::FeatureNorm_MAX;
constexpr int GenericFeatureVector::FeatureNorm_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class GenericFeatureVector_Crowding::_Internal {
 public:
  using HasBits = decltype(std::declval<GenericFeatureVector_Crowding>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GenericFeatureVector_Crowding, _impl_._has_bits_);
  static void set_has_crowding_attribute(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

GenericFeatureVector_Crowding::GenericFeatureVector_Crowding(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.GenericFeatureVector.Crowding)
}
GenericFeatureVector_Crowding::GenericFeatureVector_Crowding(
    ::google::protobuf::Arena* arena, const GenericFeatureVector_Crowding& from)
    : GenericFeatureVector_Crowding(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector_Crowding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GenericFeatureVector_Crowding::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.crowding_attribute_ = {};
}
GenericFeatureVector_Crowding::~GenericFeatureVector_Crowding() {
  // @@protoc_insertion_point(destructor:research_scann.GenericFeatureVector.Crowding)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GenericFeatureVector_Crowding::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GenericFeatureVector_Crowding::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.GenericFeatureVector.Crowding)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.crowding_attribute_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GenericFeatureVector_Crowding::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GenericFeatureVector_Crowding::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GenericFeatureVector_Crowding, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GenericFeatureVector_Crowding_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional int64 crowding_attribute = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GenericFeatureVector_Crowding, _impl_.crowding_attribute_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_Crowding, _impl_.crowding_attribute_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 crowding_attribute = 1;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_Crowding, _impl_.crowding_attribute_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* GenericFeatureVector_Crowding::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.GenericFeatureVector.Crowding)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 crowding_attribute = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_crowding_attribute(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.GenericFeatureVector.Crowding)
  return target;
}

::size_t GenericFeatureVector_Crowding::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.GenericFeatureVector.Crowding)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional int64 crowding_attribute = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_crowding_attribute());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GenericFeatureVector_Crowding::_class_data_ = {
    GenericFeatureVector_Crowding::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GenericFeatureVector_Crowding::GetClassData() const {
  return &_class_data_;
}

void GenericFeatureVector_Crowding::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GenericFeatureVector_Crowding*>(&to_msg);
  auto& from = static_cast<const GenericFeatureVector_Crowding&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.GenericFeatureVector.Crowding)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_crowding_attribute(from._internal_crowding_attribute());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenericFeatureVector_Crowding::CopyFrom(const GenericFeatureVector_Crowding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.GenericFeatureVector.Crowding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GenericFeatureVector_Crowding::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GenericFeatureVector_Crowding::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GenericFeatureVector_Crowding::InternalSwap(GenericFeatureVector_Crowding* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.crowding_attribute_, other->_impl_.crowding_attribute_);
}

::google::protobuf::Metadata GenericFeatureVector_Crowding::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_getter, &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once,
      file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto[0]);
}
// ===================================================================

class GenericFeatureVector_RestrictTokens::_Internal {
 public:
  using HasBits = decltype(std::declval<GenericFeatureVector_RestrictTokens>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::research_scann::GenericFeatureVector_RestrictTokens, _impl_._oneof_case_);
  static const ::research_scann::V3Restrict& v3(const GenericFeatureVector_RestrictTokens* msg);
  static void set_has_v3(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::research_scann::coscann::EasyRestrictDefinition& easy_definition(const GenericFeatureVector_RestrictTokens* msg);
  static const ::research_scann::coscann::RestrictTokensV2& tokens(const GenericFeatureVector_RestrictTokens* msg);
  static const ::research_scann::coscann::RestrictDefinition& definition(const GenericFeatureVector_RestrictTokens* msg);
  static void set_has_v3_compatible_namespace(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::research_scann::V3Restrict& GenericFeatureVector_RestrictTokens::_Internal::v3(const GenericFeatureVector_RestrictTokens* msg) {
  return *msg->_impl_.v3_;
}
const ::research_scann::coscann::EasyRestrictDefinition& GenericFeatureVector_RestrictTokens::_Internal::easy_definition(const GenericFeatureVector_RestrictTokens* msg) {
  return *msg->_impl_.v2_restricts_.easy_definition_;
}
const ::research_scann::coscann::RestrictTokensV2& GenericFeatureVector_RestrictTokens::_Internal::tokens(const GenericFeatureVector_RestrictTokens* msg) {
  return *msg->_impl_.v2_restricts_.tokens_;
}
const ::research_scann::coscann::RestrictDefinition& GenericFeatureVector_RestrictTokens::_Internal::definition(const GenericFeatureVector_RestrictTokens* msg) {
  return *msg->_impl_.v2_restricts_.definition_;
}
void GenericFeatureVector_RestrictTokens::clear_v3() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.v3_ != nullptr) _impl_.v3_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void GenericFeatureVector_RestrictTokens::set_allocated_easy_definition(::research_scann::coscann::EasyRestrictDefinition* easy_definition) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_v2_restricts();
  if (easy_definition) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(easy_definition)->GetArena();
    if (message_arena != submessage_arena) {
      easy_definition = ::google::protobuf::internal::GetOwnedMessage(message_arena, easy_definition, submessage_arena);
    }
    set_has_easy_definition();
    _impl_.v2_restricts_.easy_definition_ = easy_definition;
  }
  // @@protoc_insertion_point(field_set_allocated:research_scann.GenericFeatureVector.RestrictTokens.easy_definition)
}
void GenericFeatureVector_RestrictTokens::clear_easy_definition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (v2_restricts_case() == kEasyDefinition) {
    if (GetArena() == nullptr) {
      delete _impl_.v2_restricts_.easy_definition_;
    }
    clear_has_v2_restricts();
  }
}
void GenericFeatureVector_RestrictTokens::set_allocated_tokens(::research_scann::coscann::RestrictTokensV2* tokens) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_v2_restricts();
  if (tokens) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(tokens)->GetArena();
    if (message_arena != submessage_arena) {
      tokens = ::google::protobuf::internal::GetOwnedMessage(message_arena, tokens, submessage_arena);
    }
    set_has_tokens();
    _impl_.v2_restricts_.tokens_ = tokens;
  }
  // @@protoc_insertion_point(field_set_allocated:research_scann.GenericFeatureVector.RestrictTokens.tokens)
}
void GenericFeatureVector_RestrictTokens::clear_tokens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (v2_restricts_case() == kTokens) {
    if (GetArena() == nullptr) {
      delete _impl_.v2_restricts_.tokens_;
    }
    clear_has_v2_restricts();
  }
}
void GenericFeatureVector_RestrictTokens::set_allocated_definition(::research_scann::coscann::RestrictDefinition* definition) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_v2_restricts();
  if (definition) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(definition)->GetArena();
    if (message_arena != submessage_arena) {
      definition = ::google::protobuf::internal::GetOwnedMessage(message_arena, definition, submessage_arena);
    }
    set_has_definition();
    _impl_.v2_restricts_.definition_ = definition;
  }
  // @@protoc_insertion_point(field_set_allocated:research_scann.GenericFeatureVector.RestrictTokens.definition)
}
void GenericFeatureVector_RestrictTokens::clear_definition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (v2_restricts_case() == kDefinition) {
    if (GetArena() == nullptr) {
      delete _impl_.v2_restricts_.definition_;
    }
    clear_has_v2_restricts();
  }
}
GenericFeatureVector_RestrictTokens::GenericFeatureVector_RestrictTokens(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.GenericFeatureVector.RestrictTokens)
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector_RestrictTokens::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        token_membership_{visibility, arena, from.token_membership_},
        _token_membership_cached_byte_size_{0},
        whitelist_token_{visibility, arena, from.whitelist_token_},
        _whitelist_token_cached_byte_size_{0},
        blacklist_token_{visibility, arena, from.blacklist_token_},
        _blacklist_token_cached_byte_size_{0},
        v3_compatible_namespace_(arena, from.v3_compatible_namespace_),
        v2_restricts_{},
        _oneof_case_{from._oneof_case_[0]} {}

GenericFeatureVector_RestrictTokens::GenericFeatureVector_RestrictTokens(
    ::google::protobuf::Arena* arena,
    const GenericFeatureVector_RestrictTokens& from)
    : ::google::protobuf::Message(arena) {
  GenericFeatureVector_RestrictTokens* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.v3_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::research_scann::V3Restrict>(arena, *from._impl_.v3_)
                : nullptr;
  switch (v2_restricts_case()) {
    case V2_RESTRICTS_NOT_SET:
      break;
      case kEasyDefinition:
        _impl_.v2_restricts_.easy_definition_ = CreateMaybeMessage<::research_scann::coscann::EasyRestrictDefinition>(arena, *from._impl_.v2_restricts_.easy_definition_);
        break;
      case kTokens:
        _impl_.v2_restricts_.tokens_ = CreateMaybeMessage<::research_scann::coscann::RestrictTokensV2>(arena, *from._impl_.v2_restricts_.tokens_);
        break;
      case kDefinition:
        _impl_.v2_restricts_.definition_ = CreateMaybeMessage<::research_scann::coscann::RestrictDefinition>(arena, *from._impl_.v2_restricts_.definition_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:research_scann.GenericFeatureVector.RestrictTokens)
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector_RestrictTokens::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        token_membership_{visibility, arena},
        _token_membership_cached_byte_size_{0},
        whitelist_token_{visibility, arena},
        _whitelist_token_cached_byte_size_{0},
        blacklist_token_{visibility, arena},
        _blacklist_token_cached_byte_size_{0},
        v3_compatible_namespace_(arena),
        v2_restricts_{},
        _oneof_case_{} {}

inline void GenericFeatureVector_RestrictTokens::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.v3_ = {};
}
GenericFeatureVector_RestrictTokens::~GenericFeatureVector_RestrictTokens() {
  // @@protoc_insertion_point(destructor:research_scann.GenericFeatureVector.RestrictTokens)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GenericFeatureVector_RestrictTokens::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.v3_compatible_namespace_.Destroy();
  delete _impl_.v3_;
  if (has_v2_restricts()) {
    clear_v2_restricts();
  }
  _impl_.~Impl_();
}

void GenericFeatureVector_RestrictTokens::clear_v2_restricts() {
// @@protoc_insertion_point(one_of_clear_start:research_scann.GenericFeatureVector.RestrictTokens)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (v2_restricts_case()) {
    case kEasyDefinition: {
      if (GetArena() == nullptr) {
        delete _impl_.v2_restricts_.easy_definition_;
      }
      break;
    }
    case kTokens: {
      if (GetArena() == nullptr) {
        delete _impl_.v2_restricts_.tokens_;
      }
      break;
    }
    case kDefinition: {
      if (GetArena() == nullptr) {
        delete _impl_.v2_restricts_.definition_;
      }
      break;
    }
    case V2_RESTRICTS_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = V2_RESTRICTS_NOT_SET;
}


PROTOBUF_NOINLINE void GenericFeatureVector_RestrictTokens::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.GenericFeatureVector.RestrictTokens)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_membership_.Clear();
  _impl_.whitelist_token_.Clear();
  _impl_.blacklist_token_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.v3_compatible_namespace_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.v3_ != nullptr);
      _impl_.v3_->Clear();
    }
  }
  clear_v2_restricts();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GenericFeatureVector_RestrictTokens::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 4, 90, 2> GenericFeatureVector_RestrictTokens::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GenericFeatureVector_RestrictTokens_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string v3_compatible_namespace = 8;
    {::_pbi::TcParser::FastSS1,
     {66, 0, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v3_compatible_namespace_)}},
    // repeated int64 token_membership = 1 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.token_membership_)}},
    // repeated int64 whitelist_token = 2 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.whitelist_token_)}},
    // repeated int64 blacklist_token = 3 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.blacklist_token_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional .research_scann.V3Restrict v3 = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 1, 3, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v3_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int64 token_membership = 1 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.token_membership_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
    // repeated int64 whitelist_token = 2 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.whitelist_token_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
    // repeated int64 blacklist_token = 3 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.blacklist_token_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
    // .research_scann.coscann.RestrictDefinition definition = 4;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v2_restricts_.definition_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .research_scann.coscann.RestrictTokensV2 tokens = 5;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v2_restricts_.tokens_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .research_scann.coscann.EasyRestrictDefinition easy_definition = 6;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v2_restricts_.easy_definition_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .research_scann.V3Restrict v3 = 7;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v3_), _Internal::kHasBitsOffset + 1, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string v3_compatible_namespace = 8;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_RestrictTokens, _impl_.v3_compatible_namespace_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::research_scann::coscann::RestrictDefinition>()},
    {::_pbi::TcParser::GetTable<::research_scann::coscann::RestrictTokensV2>()},
    {::_pbi::TcParser::GetTable<::research_scann::coscann::EasyRestrictDefinition>()},
    {::_pbi::TcParser::GetTable<::research_scann::V3Restrict>()},
  }}, {{
    "\62\0\0\0\0\0\0\0\27\0\0\0\0\0\0\0"
    "research_scann.GenericFeatureVector.RestrictTokens"
    "v3_compatible_namespace"
  }},
};

::uint8_t* GenericFeatureVector_RestrictTokens::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.GenericFeatureVector.RestrictTokens)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int64 token_membership = 1 [packed = true];
  {
    int byte_size = _impl_._token_membership_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          1, _internal_token_membership(), byte_size, target);
    }
  }

  // repeated int64 whitelist_token = 2 [packed = true];
  {
    int byte_size = _impl_._whitelist_token_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          2, _internal_whitelist_token(), byte_size, target);
    }
  }

  // repeated int64 blacklist_token = 3 [packed = true];
  {
    int byte_size = _impl_._blacklist_token_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          3, _internal_blacklist_token(), byte_size, target);
    }
  }

  switch (v2_restricts_case()) {
    case kDefinition: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, _Internal::definition(this),
          _Internal::definition(this).GetCachedSize(), target, stream);
      break;
    }
    case kTokens: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, _Internal::tokens(this),
          _Internal::tokens(this).GetCachedSize(), target, stream);
      break;
    }
    case kEasyDefinition: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, _Internal::easy_definition(this),
          _Internal::easy_definition(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  cached_has_bits = _impl_._has_bits_[0];
  // optional .research_scann.V3Restrict v3 = 7;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, _Internal::v3(this),
        _Internal::v3(this).GetCachedSize(), target, stream);
  }

  // optional string v3_compatible_namespace = 8;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_v3_compatible_namespace();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "research_scann.GenericFeatureVector.RestrictTokens.v3_compatible_namespace");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.GenericFeatureVector.RestrictTokens)
  return target;
}

::size_t GenericFeatureVector_RestrictTokens::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.GenericFeatureVector.RestrictTokens)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 token_membership = 1 [packed = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_token_membership())
    ;
    _impl_._token_membership_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated int64 whitelist_token = 2 [packed = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_whitelist_token())
    ;
    _impl_._whitelist_token_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated int64 blacklist_token = 3 [packed = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_blacklist_token())
    ;
    _impl_._blacklist_token_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string v3_compatible_namespace = 8;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_v3_compatible_namespace());
    }

    // optional .research_scann.V3Restrict v3 = 7;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v3_);
    }

  }
  switch (v2_restricts_case()) {
    // .research_scann.coscann.EasyRestrictDefinition easy_definition = 6;
    case kEasyDefinition: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v2_restricts_.easy_definition_);
      break;
    }
    // .research_scann.coscann.RestrictTokensV2 tokens = 5;
    case kTokens: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v2_restricts_.tokens_);
      break;
    }
    // .research_scann.coscann.RestrictDefinition definition = 4;
    case kDefinition: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v2_restricts_.definition_);
      break;
    }
    case V2_RESTRICTS_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GenericFeatureVector_RestrictTokens::_class_data_ = {
    GenericFeatureVector_RestrictTokens::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GenericFeatureVector_RestrictTokens::GetClassData() const {
  return &_class_data_;
}

void GenericFeatureVector_RestrictTokens::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GenericFeatureVector_RestrictTokens*>(&to_msg);
  auto& from = static_cast<const GenericFeatureVector_RestrictTokens&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.GenericFeatureVector.RestrictTokens)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_token_membership()->MergeFrom(from._internal_token_membership());
  _this->_internal_mutable_whitelist_token()->MergeFrom(from._internal_whitelist_token());
  _this->_internal_mutable_blacklist_token()->MergeFrom(from._internal_blacklist_token());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_v3_compatible_namespace(from._internal_v3_compatible_namespace());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_v3()->::research_scann::V3Restrict::MergeFrom(
          from._internal_v3());
    }
  }
  switch (from.v2_restricts_case()) {
    case kEasyDefinition: {
      _this->_internal_mutable_easy_definition()->::research_scann::coscann::EasyRestrictDefinition::MergeFrom(
          from._internal_easy_definition());
      break;
    }
    case kTokens: {
      _this->_internal_mutable_tokens()->::research_scann::coscann::RestrictTokensV2::MergeFrom(
          from._internal_tokens());
      break;
    }
    case kDefinition: {
      _this->_internal_mutable_definition()->::research_scann::coscann::RestrictDefinition::MergeFrom(
          from._internal_definition());
      break;
    }
    case V2_RESTRICTS_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenericFeatureVector_RestrictTokens::CopyFrom(const GenericFeatureVector_RestrictTokens& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.GenericFeatureVector.RestrictTokens)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GenericFeatureVector_RestrictTokens::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GenericFeatureVector_RestrictTokens::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GenericFeatureVector_RestrictTokens::InternalSwap(GenericFeatureVector_RestrictTokens* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.token_membership_.InternalSwap(&other->_impl_.token_membership_);
  _impl_.whitelist_token_.InternalSwap(&other->_impl_.whitelist_token_);
  _impl_.blacklist_token_.InternalSwap(&other->_impl_.blacklist_token_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.v3_compatible_namespace_, &other->_impl_.v3_compatible_namespace_, arena);
  swap(_impl_.v3_, other->_impl_.v3_);
  swap(_impl_.v2_restricts_, other->_impl_.v2_restricts_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata GenericFeatureVector_RestrictTokens::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_getter, &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once,
      file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto[1]);
}
// ===================================================================

class GenericFeatureVector_FixedPointMetadata::_Internal {
 public:
  using HasBits = decltype(std::declval<GenericFeatureVector_FixedPointMetadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GenericFeatureVector_FixedPointMetadata, _impl_._has_bits_);
  static void set_has_squared_l2_norm(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

GenericFeatureVector_FixedPointMetadata::GenericFeatureVector_FixedPointMetadata(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.GenericFeatureVector.FixedPointMetadata)
}
GenericFeatureVector_FixedPointMetadata::GenericFeatureVector_FixedPointMetadata(
    ::google::protobuf::Arena* arena, const GenericFeatureVector_FixedPointMetadata& from)
    : GenericFeatureVector_FixedPointMetadata(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector_FixedPointMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GenericFeatureVector_FixedPointMetadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.squared_l2_norm_ = {};
}
GenericFeatureVector_FixedPointMetadata::~GenericFeatureVector_FixedPointMetadata() {
  // @@protoc_insertion_point(destructor:research_scann.GenericFeatureVector.FixedPointMetadata)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GenericFeatureVector_FixedPointMetadata::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GenericFeatureVector_FixedPointMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.GenericFeatureVector.FixedPointMetadata)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.squared_l2_norm_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GenericFeatureVector_FixedPointMetadata::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GenericFeatureVector_FixedPointMetadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GenericFeatureVector_FixedPointMetadata, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GenericFeatureVector_FixedPointMetadata_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional float squared_l2_norm = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector_FixedPointMetadata, _impl_.squared_l2_norm_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float squared_l2_norm = 1;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector_FixedPointMetadata, _impl_.squared_l2_norm_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* GenericFeatureVector_FixedPointMetadata::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.GenericFeatureVector.FixedPointMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional float squared_l2_norm = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_squared_l2_norm(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.GenericFeatureVector.FixedPointMetadata)
  return target;
}

::size_t GenericFeatureVector_FixedPointMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.GenericFeatureVector.FixedPointMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional float squared_l2_norm = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GenericFeatureVector_FixedPointMetadata::_class_data_ = {
    GenericFeatureVector_FixedPointMetadata::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GenericFeatureVector_FixedPointMetadata::GetClassData() const {
  return &_class_data_;
}

void GenericFeatureVector_FixedPointMetadata::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GenericFeatureVector_FixedPointMetadata*>(&to_msg);
  auto& from = static_cast<const GenericFeatureVector_FixedPointMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.GenericFeatureVector.FixedPointMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_squared_l2_norm(from._internal_squared_l2_norm());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenericFeatureVector_FixedPointMetadata::CopyFrom(const GenericFeatureVector_FixedPointMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.GenericFeatureVector.FixedPointMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GenericFeatureVector_FixedPointMetadata::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GenericFeatureVector_FixedPointMetadata::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GenericFeatureVector_FixedPointMetadata::InternalSwap(GenericFeatureVector_FixedPointMetadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.squared_l2_norm_, other->_impl_.squared_l2_norm_);
}

::google::protobuf::Metadata GenericFeatureVector_FixedPointMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_getter, &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once,
      file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto[2]);
}
// ===================================================================

class GenericFeatureVector::_Internal {
 public:
  using HasBits = decltype(std::declval<GenericFeatureVector>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_._has_bits_);
  static void set_has_feature_type(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_data_id_str(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_feature_value_string(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_norm_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_class_label(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::research_scann::GenericFeatureVector_Crowding& crowding(const GenericFeatureVector* msg);
  static void set_has_crowding(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static const ::research_scann::GenericFeatureVector_RestrictTokens& restrict_tokens(const GenericFeatureVector* msg);
  static void set_has_restrict_tokens(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::research_scann::GenericFeatureVector_FixedPointMetadata& fixed_point_metadata(const GenericFeatureVector* msg);
  static void set_has_fixed_point_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_userinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::google::protobuf::Timestamp& expiration_timestamp(const GenericFeatureVector* msg);
  static void set_has_expiration_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_feature_dim(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_weight(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000100) ^ 0x00000100) != 0;
  }
};

const ::research_scann::GenericFeatureVector_Crowding& GenericFeatureVector::_Internal::crowding(const GenericFeatureVector* msg) {
  return *msg->_impl_.crowding_;
}
const ::research_scann::GenericFeatureVector_RestrictTokens& GenericFeatureVector::_Internal::restrict_tokens(const GenericFeatureVector* msg) {
  return *msg->_impl_.restrict_tokens_;
}
const ::research_scann::GenericFeatureVector_FixedPointMetadata& GenericFeatureVector::_Internal::fixed_point_metadata(const GenericFeatureVector* msg) {
  return *msg->_impl_.fixed_point_metadata_;
}
const ::google::protobuf::Timestamp& GenericFeatureVector::_Internal::expiration_timestamp(const GenericFeatureVector* msg) {
  return *msg->_impl_.expiration_timestamp_;
}
void GenericFeatureVector::clear_expiration_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.expiration_timestamp_ != nullptr) _impl_.expiration_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
GenericFeatureVector::GenericFeatureVector(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &GenericFeatureVector::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:research_scann.GenericFeatureVector)
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        feature_value_int64_{visibility, arena, from.feature_value_int64_},
        _feature_value_int64_cached_byte_size_{0},
        feature_value_float_{visibility, arena, from.feature_value_float_},
        feature_value_double_{visibility, arena, from.feature_value_double_},
        feature_index_{visibility, arena, from.feature_index_},
        _feature_index_cached_byte_size_{0},
        tokens_{visibility, arena, from.tokens_},
        _tokens_cached_byte_size_{0},
        data_id_str_(arena, from.data_id_str_),
        feature_value_string_(arena, from.feature_value_string_),
        class_label_(arena, from.class_label_),
        userinfo_{from.userinfo_} {}

GenericFeatureVector::GenericFeatureVector(
    ::google::protobuf::Arena* arena,
    const GenericFeatureVector& from)
    : ::google::protobuf::Message(arena) {
  GenericFeatureVector* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.restrict_tokens_ = (cached_has_bits & 0x00000010u)
                ? CreateMaybeMessage<::research_scann::GenericFeatureVector_RestrictTokens>(arena, *from._impl_.restrict_tokens_)
                : nullptr;
  _impl_.crowding_ = (cached_has_bits & 0x00000020u)
                ? CreateMaybeMessage<::research_scann::GenericFeatureVector_Crowding>(arena, *from._impl_.crowding_)
                : nullptr;
  _impl_.fixed_point_metadata_ = (cached_has_bits & 0x00000040u)
                ? CreateMaybeMessage<::research_scann::GenericFeatureVector_FixedPointMetadata>(arena, *from._impl_.fixed_point_metadata_)
                : nullptr;
  _impl_.expiration_timestamp_ = (cached_has_bits & 0x00000080u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.expiration_timestamp_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, feature_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, feature_type_),
           offsetof(Impl_, feature_dim_) -
               offsetof(Impl_, feature_type_) +
               sizeof(Impl_::feature_dim_));
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &GenericFeatureVector::ArenaDtor);
  }

  // @@protoc_insertion_point(copy_constructor:research_scann.GenericFeatureVector)
}
inline PROTOBUF_NDEBUG_INLINE GenericFeatureVector::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        feature_value_int64_{visibility, arena},
        _feature_value_int64_cached_byte_size_{0},
        feature_value_float_{visibility, arena},
        feature_value_double_{visibility, arena},
        feature_index_{visibility, arena},
        _feature_index_cached_byte_size_{0},
        tokens_{visibility, arena},
        _tokens_cached_byte_size_{0},
        data_id_str_(arena),
        feature_value_string_(arena),
        class_label_(arena),
        userinfo_{},
        feature_dim_{::uint64_t{18446744073709551615u}} {}

inline void GenericFeatureVector::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, restrict_tokens_),
           0,
           offsetof(Impl_, norm_type_) -
               offsetof(Impl_, restrict_tokens_) +
               sizeof(Impl_::norm_type_));
}
GenericFeatureVector::~GenericFeatureVector() {
  // @@protoc_insertion_point(destructor:research_scann.GenericFeatureVector)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GenericFeatureVector::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_id_str_.Destroy();
  _impl_.feature_value_string_.Destroy();
  _impl_.class_label_.Destroy();
  delete _impl_.restrict_tokens_;
  delete _impl_.crowding_;
  delete _impl_.fixed_point_metadata_;
  delete _impl_.expiration_timestamp_;
  _impl_.~Impl_();
}
void GenericFeatureVector::ArenaDtor(void* object) {
  GenericFeatureVector* _this = reinterpret_cast<GenericFeatureVector*>(object);
  _this->_impl_.userinfo_. ::absl::Cord::~Cord ();
}

PROTOBUF_NOINLINE void GenericFeatureVector::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.GenericFeatureVector)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  _impl_.feature_value_int64_.Clear();
  _impl_.feature_value_float_.Clear();
  _impl_.feature_value_double_.Clear();
  _impl_.feature_index_.Clear();
  _impl_.tokens_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.data_id_str_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.feature_value_string_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.class_label_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.userinfo_.Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.restrict_tokens_ != nullptr);
      _impl_.restrict_tokens_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(_impl_.crowding_ != nullptr);
      _impl_.crowding_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      ABSL_DCHECK(_impl_.fixed_point_metadata_ != nullptr);
      _impl_.fixed_point_metadata_->Clear();
    }
    if (cached_has_bits & 0x00000080u) {
      ABSL_DCHECK(_impl_.expiration_timestamp_ != nullptr);
      _impl_.expiration_timestamp_->Clear();
    }
  }
  if (cached_has_bits & 0x00000f00u) {
    ::memset(&_impl_.feature_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.norm_type_) -
        reinterpret_cast<char*>(&_impl_.feature_type_)) + sizeof(_impl_.norm_type_));
    _impl_.feature_dim_ = ::uint64_t{18446744073709551615u};
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GenericFeatureVector::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 17, 6, 71, 2> GenericFeatureVector::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_._extensions_),
    20, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4293921856,  // skipmap
    offsetof(decltype(_table_), field_entries),
    17,  // num_field_entries
    6,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GenericFeatureVector_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required .research_scann.GenericFeatureVector.FeatureType feature_type = 1;
    {::_pbi::TcParser::FastEr0S1,
     {8, 8, 5, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_type_)}},
    // optional bytes data_id_str = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.data_id_str_)}},
    // repeated int64 feature_value_int64 = 3 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_int64_)}},
    // repeated float feature_value_float = 4 [packed = true];
    {::_pbi::TcParser::FastF32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_float_)}},
    // repeated double feature_value_double = 5 [packed = true];
    {::_pbi::TcParser::FastF64P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_double_)}},
    // repeated uint64 feature_index = 6 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_index_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional float weight = 8 [deprecated = true];
    {::_pbi::TcParser::FastF32S1,
     {69, 9, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.weight_)}},
    // optional .research_scann.GenericFeatureVector.FeatureNorm norm_type = 9 [default = NONE];
    {::_pbi::TcParser::FastEr0S1,
     {72, 10, 3, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.norm_type_)}},
    // optional uint64 feature_dim = 10 [default = 18446744073709551615, deprecated = true];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GenericFeatureVector, _impl_.feature_dim_), 11>(),
     {80, 11, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_dim_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional bytes feature_value_string = 13;
    {::_pbi::TcParser::FastBS1,
     {106, 1, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_string_)}},
    // repeated int32 tokens = 14 [packed = true, deprecated = true];
    {::_pbi::TcParser::FastV32P1,
     {114, 63, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.tokens_)}},
    // optional .research_scann.GenericFeatureVector.RestrictTokens restrict_tokens = 15;
    {::_pbi::TcParser::FastMtS1,
     {122, 4, 2, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.restrict_tokens_)}},
    // optional string class_label = 16;
    {::_pbi::TcParser::FastSS2,
     {386, 2, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.class_label_)}},
    // optional bytes userinfo = 17 [ctype = CORD];
    {::_pbi::TcParser::FastBcS2,
     {394, 3, 0, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.userinfo_)}},
    // optional .research_scann.GenericFeatureVector.Crowding crowding = 18;
    {::_pbi::TcParser::FastMtS2,
     {402, 5, 3, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.crowding_)}},
    // optional .research_scann.GenericFeatureVector.FixedPointMetadata fixed_point_metadata = 19;
    {::_pbi::TcParser::FastMtS2,
     {410, 6, 4, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.fixed_point_metadata_)}},
    // optional .google.protobuf.Timestamp expiration_timestamp = 20;
    {::_pbi::TcParser::FastMtS2,
     {418, 7, 5, PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.expiration_timestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required .research_scann.GenericFeatureVector.FeatureType feature_type = 1;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_type_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bytes data_id_str = 2;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.data_id_str_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated int64 feature_value_int64 = 3 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_int64_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
    // repeated float feature_value_float = 4 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_float_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated double feature_value_double = 5 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_double_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated uint64 feature_index = 6 [packed = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_index_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // optional float weight = 8 [deprecated = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.weight_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional .research_scann.GenericFeatureVector.FeatureNorm norm_type = 9 [default = NONE];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.norm_type_), _Internal::kHasBitsOffset + 10, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional uint64 feature_dim = 10 [default = 18446744073709551615, deprecated = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_dim_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional bytes feature_value_string = 13;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_value_string_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated int32 tokens = 14 [packed = true, deprecated = true];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.tokens_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // optional .research_scann.GenericFeatureVector.RestrictTokens restrict_tokens = 15;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.restrict_tokens_), _Internal::kHasBitsOffset + 4, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string class_label = 16;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.class_label_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional bytes userinfo = 17 [ctype = CORD];
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.userinfo_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepCord)},
    // optional .research_scann.GenericFeatureVector.Crowding crowding = 18;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.crowding_), _Internal::kHasBitsOffset + 5, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .research_scann.GenericFeatureVector.FixedPointMetadata fixed_point_metadata = 19;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.fixed_point_metadata_), _Internal::kHasBitsOffset + 6, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .google.protobuf.Timestamp expiration_timestamp = 20;
    {PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.expiration_timestamp_), _Internal::kHasBitsOffset + 7, 5,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {0, 6},
    {0, 4},
    {::_pbi::TcParser::GetTable<::research_scann::GenericFeatureVector_RestrictTokens>()},
    {::_pbi::TcParser::GetTable<::research_scann::GenericFeatureVector_Crowding>()},
    {::_pbi::TcParser::GetTable<::research_scann::GenericFeatureVector_FixedPointMetadata>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
    "\43\0\0\0\0\0\0\0\0\0\0\0\0\13\0\0\0\0\0\0\0\0\0\0"
    "research_scann.GenericFeatureVector"
    "class_label"
  }},
};

::uint8_t* GenericFeatureVector::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.GenericFeatureVector)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .research_scann.GenericFeatureVector.FeatureType feature_type = 1;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_feature_type(), target);
  }

  // optional bytes data_id_str = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_data_id_str();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // repeated int64 feature_value_int64 = 3 [packed = true];
  {
    int byte_size = _impl_._feature_value_int64_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          3, _internal_feature_value_int64(), byte_size, target);
    }
  }

  // repeated float feature_value_float = 4 [packed = true];
  if (this->_internal_feature_value_float_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_feature_value_float(), target);
  }

  // repeated double feature_value_double = 5 [packed = true];
  if (this->_internal_feature_value_double_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_feature_value_double(), target);
  }

  // repeated uint64 feature_index = 6 [packed = true];
  {
    int byte_size = _impl_._feature_index_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          6, _internal_feature_index(), byte_size, target);
    }
  }

  // optional float weight = 8 [deprecated = true];
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this->_internal_weight(), target);
  }

  // optional .research_scann.GenericFeatureVector.FeatureNorm norm_type = 9 [default = NONE];
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        9, this->_internal_norm_type(), target);
  }

  // optional uint64 feature_dim = 10 [default = 18446744073709551615, deprecated = true];
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        10, this->_internal_feature_dim(), target);
  }

  // optional bytes feature_value_string = 13;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_feature_value_string();
    target = stream->WriteBytesMaybeAliased(13, _s, target);
  }

  // repeated int32 tokens = 14 [packed = true, deprecated = true];
  {
    int byte_size = _impl_._tokens_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          14, _internal_tokens(), byte_size, target);
    }
  }

  // optional .research_scann.GenericFeatureVector.RestrictTokens restrict_tokens = 15;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        15, _Internal::restrict_tokens(this),
        _Internal::restrict_tokens(this).GetCachedSize(), target, stream);
  }

  // optional string class_label = 16;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_class_label();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "research_scann.GenericFeatureVector.class_label");
    target = stream->WriteStringMaybeAliased(16, _s, target);
  }

  // optional bytes userinfo = 17 [ctype = CORD];
  if (cached_has_bits & 0x00000008u) {
    target = stream->WriteBytes(17, this->_internal_userinfo(), target);
  }

  // optional .research_scann.GenericFeatureVector.Crowding crowding = 18;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        18, _Internal::crowding(this),
        _Internal::crowding(this).GetCachedSize(), target, stream);
  }

  // optional .research_scann.GenericFeatureVector.FixedPointMetadata fixed_point_metadata = 19;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        19, _Internal::fixed_point_metadata(this),
        _Internal::fixed_point_metadata(this).GetCachedSize(), target, stream);
  }

  // optional .google.protobuf.Timestamp expiration_timestamp = 20;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        20, _Internal::expiration_timestamp(this),
        _Internal::expiration_timestamp(this).GetCachedSize(), target, stream);
  }

  // Extension range [1000, 536870912)
  target = _impl_._extensions_._InternalSerialize(
      internal_default_instance(), 1000, 536870912, target, stream);
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.GenericFeatureVector)
  return target;
}

::size_t GenericFeatureVector::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.GenericFeatureVector)
  ::size_t total_size = 0;

  total_size += _impl_._extensions_.ByteSize();

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 feature_value_int64 = 3 [packed = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_feature_value_int64())
    ;
    _impl_._feature_value_int64_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float feature_value_float = 4 [packed = true];
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_feature_value_float_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated double feature_value_double = 5 [packed = true];
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_feature_value_double_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated uint64 feature_index = 6 [packed = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt64Size(
        this->_internal_feature_index())
    ;
    _impl_._feature_index_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated int32 tokens = 14 [packed = true, deprecated = true];
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_tokens())
    ;
    _impl_._tokens_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes data_id_str = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_data_id_str());
    }

    // optional bytes feature_value_string = 13;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_feature_value_string());
    }

    // optional string class_label = 16;
    if (cached_has_bits & 0x00000004u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_class_label());
    }

    // optional bytes userinfo = 17 [ctype = CORD];
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->_internal_userinfo());
    }

    // optional .research_scann.GenericFeatureVector.RestrictTokens restrict_tokens = 15;
    if (cached_has_bits & 0x00000010u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.restrict_tokens_);
    }

    // optional .research_scann.GenericFeatureVector.Crowding crowding = 18;
    if (cached_has_bits & 0x00000020u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.crowding_);
    }

    // optional .research_scann.GenericFeatureVector.FixedPointMetadata fixed_point_metadata = 19;
    if (cached_has_bits & 0x00000040u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.fixed_point_metadata_);
    }

    // optional .google.protobuf.Timestamp expiration_timestamp = 20;
    if (cached_has_bits & 0x00000080u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.expiration_timestamp_);
    }

  }
  // required .research_scann.GenericFeatureVector.FeatureType feature_type = 1;
  if (cached_has_bits & 0x00000100u) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_feature_type());
  }

  if (cached_has_bits & 0x00000e00u) {
    // optional float weight = 8 [deprecated = true];
    if (cached_has_bits & 0x00000200u) {
      total_size += 5;
    }

    // optional .research_scann.GenericFeatureVector.FeatureNorm norm_type = 9 [default = NONE];
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_norm_type());
    }

    // optional uint64 feature_dim = 10 [default = 18446744073709551615, deprecated = true];
    if (cached_has_bits & 0x00000800u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_feature_dim());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GenericFeatureVector::_class_data_ = {
    GenericFeatureVector::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GenericFeatureVector::GetClassData() const {
  return &_class_data_;
}

void GenericFeatureVector::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GenericFeatureVector*>(&to_msg);
  auto& from = static_cast<const GenericFeatureVector&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.GenericFeatureVector)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_feature_value_int64()->MergeFrom(from._internal_feature_value_int64());
  _this->_internal_mutable_feature_value_float()->MergeFrom(from._internal_feature_value_float());
  _this->_internal_mutable_feature_value_double()->MergeFrom(from._internal_feature_value_double());
  _this->_internal_mutable_feature_index()->MergeFrom(from._internal_feature_index());
  _this->_internal_mutable_tokens()->MergeFrom(from._internal_tokens());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_data_id_str(from._internal_data_id_str());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_feature_value_string(from._internal_feature_value_string());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_class_label(from._internal_class_label());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_userinfo(from._internal_userinfo());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_mutable_restrict_tokens()->::research_scann::GenericFeatureVector_RestrictTokens::MergeFrom(
          from._internal_restrict_tokens());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_mutable_crowding()->::research_scann::GenericFeatureVector_Crowding::MergeFrom(
          from._internal_crowding());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_mutable_fixed_point_metadata()->::research_scann::GenericFeatureVector_FixedPointMetadata::MergeFrom(
          from._internal_fixed_point_metadata());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_mutable_expiration_timestamp()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_expiration_timestamp());
    }
  }
  if (cached_has_bits & 0x00000f00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.feature_type_ = from._impl_.feature_type_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.weight_ = from._impl_.weight_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.norm_type_ = from._impl_.norm_type_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.feature_dim_ = from._impl_.feature_dim_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenericFeatureVector::CopyFrom(const GenericFeatureVector& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.GenericFeatureVector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GenericFeatureVector::IsInitialized() const {
  if (!_impl_._extensions_.IsInitialized(internal_default_instance())) {
    return false;
  }
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* GenericFeatureVector::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GenericFeatureVector::InternalSwap(GenericFeatureVector* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.feature_value_int64_.InternalSwap(&other->_impl_.feature_value_int64_);
  _impl_.feature_value_float_.InternalSwap(&other->_impl_.feature_value_float_);
  _impl_.feature_value_double_.InternalSwap(&other->_impl_.feature_value_double_);
  _impl_.feature_index_.InternalSwap(&other->_impl_.feature_index_);
  _impl_.tokens_.InternalSwap(&other->_impl_.tokens_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_id_str_, &other->_impl_.data_id_str_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.feature_value_string_, &other->_impl_.feature_value_string_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.class_label_, &other->_impl_.class_label_, arena);
  _impl_.userinfo_.swap(other->_impl_.userinfo_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.feature_dim_)
      + sizeof(GenericFeatureVector::_impl_.feature_dim_)
      - PROTOBUF_FIELD_OFFSET(GenericFeatureVector, _impl_.restrict_tokens_)>(
          reinterpret_cast<char*>(&_impl_.restrict_tokens_),
          reinterpret_cast<char*>(&other->_impl_.restrict_tokens_));
}

::google::protobuf::Metadata GenericFeatureVector::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_getter, &descriptor_table_scann_2fdata_5fformat_2ffeatures_2eproto_once,
      file_level_metadata_scann_2fdata_5fformat_2ffeatures_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
