// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_codes.proto

#include "error_codes.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace tensorflow {
namespace error {
}  // namespace error
}  // namespace tensorflow
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_error_5fcodes_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_error_5fcodes_2eproto = nullptr;
const ::uint32_t TableStruct_error_5fcodes_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_error_5fcodes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021error_codes.proto\022\020tensorflow.error*\204\003"
    "\n\004Code\022\006\n\002OK\020\000\022\r\n\tCANCELLED\020\001\022\013\n\007UNKNOWN"
    "\020\002\022\024\n\020INVALID_ARGUMENT\020\003\022\025\n\021DEADLINE_EXC"
    "EEDED\020\004\022\r\n\tNOT_FOUND\020\005\022\022\n\016ALREADY_EXISTS"
    "\020\006\022\025\n\021PERMISSION_DENIED\020\007\022\023\n\017UNAUTHENTIC"
    "ATED\020\020\022\026\n\022RESOURCE_EXHAUSTED\020\010\022\027\n\023FAILED"
    "_PRECONDITION\020\t\022\013\n\007ABORTED\020\n\022\020\n\014OUT_OF_R"
    "ANGE\020\013\022\021\n\rUNIMPLEMENTED\020\014\022\014\n\010INTERNAL\020\r\022"
    "\017\n\013UNAVAILABLE\020\016\022\r\n\tDATA_LOSS\020\017\022K\nGDO_NO"
    "T_USE_RESERVED_FOR_FUTURE_EXPANSION_USE_"
    "DEFAULT_IN_SWITCH_INSTEAD_\020\024Bq\n\030org.tens"
    "orflow.frameworkB\020ErrorCodesProtosP\001Z>gi"
    "thub.com/google/tsl/tsl/go/protobuf/for_"
    "core_protos_go_proto\370\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_error_5fcodes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_error_5fcodes_2eproto = {
    false,
    false,
    551,
    descriptor_table_protodef_error_5fcodes_2eproto,
    "error_codes.proto",
    &descriptor_table_error_5fcodes_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_error_5fcodes_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_error_5fcodes_2eproto,
    file_level_service_descriptors_error_5fcodes_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_error_5fcodes_2eproto_getter() {
  return &descriptor_table_error_5fcodes_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_error_5fcodes_2eproto(&descriptor_table_error_5fcodes_2eproto);
namespace tensorflow {
namespace error {
const ::google::protobuf::EnumDescriptor* Code_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_error_5fcodes_2eproto);
  return file_level_enum_descriptors_error_5fcodes_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Code_internal_data_[] = {
    1114112u, 32u, 8u, };
bool Code_IsValid(int value) {
  return 0 <= value && value <= 20 && ((1179647u >> value) & 1) != 0;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace error
}  // namespace tensorflow
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
