// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/proto/crowding.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fcrowding_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fcrowding_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scann_2fproto_2fcrowding_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scann_2fproto_2fcrowding_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scann_2fproto_2fcrowding_2eproto;
namespace research_scann {
class Crowding;
struct CrowdingDefaultTypeInternal;
extern CrowdingDefaultTypeInternal _Crowding_default_instance_;
class Crowding_Offline;
struct Crowding_OfflineDefaultTypeInternal;
extern Crowding_OfflineDefaultTypeInternal _Crowding_Offline_default_instance_;
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace research_scann {

// ===================================================================


// -------------------------------------------------------------------

class Crowding_Offline final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.Crowding.Offline) */ {
 public:
  inline Crowding_Offline() : Crowding_Offline(nullptr) {}
  ~Crowding_Offline() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Crowding_Offline(::google::protobuf::internal::ConstantInitialized);

  inline Crowding_Offline(const Crowding_Offline& from)
      : Crowding_Offline(nullptr, from) {}
  Crowding_Offline(Crowding_Offline&& from) noexcept
    : Crowding_Offline() {
    *this = ::std::move(from);
  }

  inline Crowding_Offline& operator=(const Crowding_Offline& from) {
    CopyFrom(from);
    return *this;
  }
  inline Crowding_Offline& operator=(Crowding_Offline&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Crowding_Offline& default_instance() {
    return *internal_default_instance();
  }
  static inline const Crowding_Offline* internal_default_instance() {
    return reinterpret_cast<const Crowding_Offline*>(
               &_Crowding_Offline_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Crowding_Offline& a, Crowding_Offline& b) {
    a.Swap(&b);
  }
  inline void Swap(Crowding_Offline* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Crowding_Offline* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Crowding_Offline* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Crowding_Offline>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Crowding_Offline& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Crowding_Offline& from) {
    Crowding_Offline::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Crowding_Offline* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.Crowding.Offline";
  }
  protected:
  explicit Crowding_Offline(::google::protobuf::Arena* arena);
  Crowding_Offline(::google::protobuf::Arena* arena, const Crowding_Offline& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPerCrowdingAttributePreReorderingNumNeighborsFieldNumber = 1,
    kPerCrowdingAttributePostReorderingNumNeighborsFieldNumber = 2,
  };
  // optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
  bool has_per_crowding_attribute_pre_reordering_num_neighbors() const;
  void clear_per_crowding_attribute_pre_reordering_num_neighbors() ;
  ::int32_t per_crowding_attribute_pre_reordering_num_neighbors() const;
  void set_per_crowding_attribute_pre_reordering_num_neighbors(::int32_t value);

  private:
  ::int32_t _internal_per_crowding_attribute_pre_reordering_num_neighbors() const;
  void _internal_set_per_crowding_attribute_pre_reordering_num_neighbors(::int32_t value);

  public:
  // optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
  bool has_per_crowding_attribute_post_reordering_num_neighbors() const;
  void clear_per_crowding_attribute_post_reordering_num_neighbors() ;
  ::int32_t per_crowding_attribute_post_reordering_num_neighbors() const;
  void set_per_crowding_attribute_post_reordering_num_neighbors(::int32_t value);

  private:
  ::int32_t _internal_per_crowding_attribute_post_reordering_num_neighbors() const;
  void _internal_set_per_crowding_attribute_post_reordering_num_neighbors(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.Crowding.Offline)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t per_crowding_attribute_pre_reordering_num_neighbors_;
    ::int32_t per_crowding_attribute_post_reordering_num_neighbors_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fproto_2fcrowding_2eproto;
};// -------------------------------------------------------------------

class Crowding final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.Crowding) */ {
 public:
  inline Crowding() : Crowding(nullptr) {}
  ~Crowding() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Crowding(::google::protobuf::internal::ConstantInitialized);

  inline Crowding(const Crowding& from)
      : Crowding(nullptr, from) {}
  Crowding(Crowding&& from) noexcept
    : Crowding() {
    *this = ::std::move(from);
  }

  inline Crowding& operator=(const Crowding& from) {
    CopyFrom(from);
    return *this;
  }
  inline Crowding& operator=(Crowding&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Crowding& default_instance() {
    return *internal_default_instance();
  }
  static inline const Crowding* internal_default_instance() {
    return reinterpret_cast<const Crowding*>(
               &_Crowding_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Crowding& a, Crowding& b) {
    a.Swap(&b);
  }
  inline void Swap(Crowding* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Crowding* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Crowding* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Crowding>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Crowding& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Crowding& from) {
    Crowding::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Crowding* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.Crowding";
  }
  protected:
  explicit Crowding(::google::protobuf::Arena* arena);
  Crowding(::google::protobuf::Arena* arena, const Crowding& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using Offline = Crowding_Offline;

  // accessors -------------------------------------------------------

  enum : int {
    kOfflineFieldNumber = 2,
    kEnabledFieldNumber = 1,
  };
  // optional .research_scann.Crowding.Offline offline = 2;
  bool has_offline() const;
  void clear_offline() ;
  const ::research_scann::Crowding_Offline& offline() const;
  PROTOBUF_NODISCARD ::research_scann::Crowding_Offline* release_offline();
  ::research_scann::Crowding_Offline* mutable_offline();
  void set_allocated_offline(::research_scann::Crowding_Offline* value);
  void unsafe_arena_set_allocated_offline(::research_scann::Crowding_Offline* value);
  ::research_scann::Crowding_Offline* unsafe_arena_release_offline();

  private:
  const ::research_scann::Crowding_Offline& _internal_offline() const;
  ::research_scann::Crowding_Offline* _internal_mutable_offline();

  public:
  // optional bool enabled = 1 [default = false];
  bool has_enabled() const;
  void clear_enabled() ;
  bool enabled() const;
  void set_enabled(bool value);

  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.Crowding)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::research_scann::Crowding_Offline* offline_;
    bool enabled_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fproto_2fcrowding_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Crowding_Offline

// optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
inline bool Crowding_Offline::has_per_crowding_attribute_pre_reordering_num_neighbors() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Crowding_Offline::clear_per_crowding_attribute_pre_reordering_num_neighbors() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.per_crowding_attribute_pre_reordering_num_neighbors_ = 2147483647;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Crowding_Offline::per_crowding_attribute_pre_reordering_num_neighbors() const {
  // @@protoc_insertion_point(field_get:research_scann.Crowding.Offline.per_crowding_attribute_pre_reordering_num_neighbors)
  return _internal_per_crowding_attribute_pre_reordering_num_neighbors();
}
inline void Crowding_Offline::set_per_crowding_attribute_pre_reordering_num_neighbors(::int32_t value) {
  _internal_set_per_crowding_attribute_pre_reordering_num_neighbors(value);
  // @@protoc_insertion_point(field_set:research_scann.Crowding.Offline.per_crowding_attribute_pre_reordering_num_neighbors)
}
inline ::int32_t Crowding_Offline::_internal_per_crowding_attribute_pre_reordering_num_neighbors() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.per_crowding_attribute_pre_reordering_num_neighbors_;
}
inline void Crowding_Offline::_internal_set_per_crowding_attribute_pre_reordering_num_neighbors(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.per_crowding_attribute_pre_reordering_num_neighbors_ = value;
}

// optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
inline bool Crowding_Offline::has_per_crowding_attribute_post_reordering_num_neighbors() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Crowding_Offline::clear_per_crowding_attribute_post_reordering_num_neighbors() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.per_crowding_attribute_post_reordering_num_neighbors_ = 2147483647;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t Crowding_Offline::per_crowding_attribute_post_reordering_num_neighbors() const {
  // @@protoc_insertion_point(field_get:research_scann.Crowding.Offline.per_crowding_attribute_post_reordering_num_neighbors)
  return _internal_per_crowding_attribute_post_reordering_num_neighbors();
}
inline void Crowding_Offline::set_per_crowding_attribute_post_reordering_num_neighbors(::int32_t value) {
  _internal_set_per_crowding_attribute_post_reordering_num_neighbors(value);
  // @@protoc_insertion_point(field_set:research_scann.Crowding.Offline.per_crowding_attribute_post_reordering_num_neighbors)
}
inline ::int32_t Crowding_Offline::_internal_per_crowding_attribute_post_reordering_num_neighbors() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.per_crowding_attribute_post_reordering_num_neighbors_;
}
inline void Crowding_Offline::_internal_set_per_crowding_attribute_post_reordering_num_neighbors(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.per_crowding_attribute_post_reordering_num_neighbors_ = value;
}

// -------------------------------------------------------------------

// Crowding

// optional bool enabled = 1 [default = false];
inline bool Crowding::has_enabled() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Crowding::clear_enabled() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.enabled_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool Crowding::enabled() const {
  // @@protoc_insertion_point(field_get:research_scann.Crowding.enabled)
  return _internal_enabled();
}
inline void Crowding::set_enabled(bool value) {
  _internal_set_enabled(value);
  // @@protoc_insertion_point(field_set:research_scann.Crowding.enabled)
}
inline bool Crowding::_internal_enabled() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.enabled_;
}
inline void Crowding::_internal_set_enabled(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.enabled_ = value;
}

// optional .research_scann.Crowding.Offline offline = 2;
inline bool Crowding::has_offline() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.offline_ != nullptr);
  return value;
}
inline void Crowding::clear_offline() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.offline_ != nullptr) _impl_.offline_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::research_scann::Crowding_Offline& Crowding::_internal_offline() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::research_scann::Crowding_Offline* p = _impl_.offline_;
  return p != nullptr ? *p : reinterpret_cast<const ::research_scann::Crowding_Offline&>(::research_scann::_Crowding_Offline_default_instance_);
}
inline const ::research_scann::Crowding_Offline& Crowding::offline() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.Crowding.offline)
  return _internal_offline();
}
inline void Crowding::unsafe_arena_set_allocated_offline(::research_scann::Crowding_Offline* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.offline_);
  }
  _impl_.offline_ = reinterpret_cast<::research_scann::Crowding_Offline*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.Crowding.offline)
}
inline ::research_scann::Crowding_Offline* Crowding::release_offline() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::Crowding_Offline* released = _impl_.offline_;
  _impl_.offline_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::research_scann::Crowding_Offline* Crowding::unsafe_arena_release_offline() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.Crowding.offline)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::Crowding_Offline* temp = _impl_.offline_;
  _impl_.offline_ = nullptr;
  return temp;
}
inline ::research_scann::Crowding_Offline* Crowding::_internal_mutable_offline() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.offline_ == nullptr) {
    auto* p = CreateMaybeMessage<::research_scann::Crowding_Offline>(GetArena());
    _impl_.offline_ = reinterpret_cast<::research_scann::Crowding_Offline*>(p);
  }
  return _impl_.offline_;
}
inline ::research_scann::Crowding_Offline* Crowding::mutable_offline() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::Crowding_Offline* _msg = _internal_mutable_offline();
  // @@protoc_insertion_point(field_mutable:research_scann.Crowding.offline)
  return _msg;
}
inline void Crowding::set_allocated_offline(::research_scann::Crowding_Offline* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::research_scann::Crowding_Offline*>(_impl_.offline_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::research_scann::Crowding_Offline*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.offline_ = reinterpret_cast<::research_scann::Crowding_Offline*>(value);
  // @@protoc_insertion_point(field_set_allocated:research_scann.Crowding.offline)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fcrowding_2eproto_2epb_2eh
