// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/proto/crowding.proto

#include "scann/proto/crowding.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace research_scann {

inline constexpr Crowding_Offline::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        per_crowding_attribute_pre_reordering_num_neighbors_{2147483647},
        per_crowding_attribute_post_reordering_num_neighbors_{2147483647} {}

template <typename>
PROTOBUF_CONSTEXPR Crowding_Offline::Crowding_Offline(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Crowding_OfflineDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Crowding_OfflineDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Crowding_OfflineDefaultTypeInternal() {}
  union {
    Crowding_Offline _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Crowding_OfflineDefaultTypeInternal _Crowding_Offline_default_instance_;

inline constexpr Crowding::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        offline_{nullptr},
        enabled_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Crowding::Crowding(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CrowdingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CrowdingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CrowdingDefaultTypeInternal() {}
  union {
    Crowding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CrowdingDefaultTypeInternal _Crowding_default_instance_;
}  // namespace research_scann
static ::_pb::Metadata file_level_metadata_scann_2fproto_2fcrowding_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_scann_2fproto_2fcrowding_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_scann_2fproto_2fcrowding_2eproto = nullptr;
const ::uint32_t TableStruct_scann_2fproto_2fcrowding_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding_Offline, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding_Offline, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding_Offline, _impl_.per_crowding_attribute_pre_reordering_num_neighbors_),
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding_Offline, _impl_.per_crowding_attribute_post_reordering_num_neighbors_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding, _impl_.enabled_),
    PROTOBUF_FIELD_OFFSET(::research_scann::Crowding, _impl_.offline_),
    1,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::research_scann::Crowding_Offline)},
        {12, 22, -1, sizeof(::research_scann::Crowding)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::research_scann::_Crowding_Offline_default_instance_._instance,
    &::research_scann::_Crowding_default_instance_._instance,
};
const char descriptor_table_protodef_scann_2fproto_2fcrowding_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032scann/proto/crowding.proto\022\016research_s"
    "cann\"\364\001\n\010Crowding\022\026\n\007enabled\030\001 \001(\010:\005fals"
    "e\0221\n\007offline\030\002 \001(\0132 .research_scann.Crow"
    "ding.Offline\032\234\001\n\007Offline\022G\n3per_crowding"
    "_attribute_pre_reordering_num_neighbors\030"
    "\001 \001(\005:\n2147483647\022H\n4per_crowding_attrib"
    "ute_post_reordering_num_neighbors\030\002 \001(\005:"
    "\n2147483647"
};
static ::absl::once_flag descriptor_table_scann_2fproto_2fcrowding_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_scann_2fproto_2fcrowding_2eproto = {
    false,
    false,
    291,
    descriptor_table_protodef_scann_2fproto_2fcrowding_2eproto,
    "scann/proto/crowding.proto",
    &descriptor_table_scann_2fproto_2fcrowding_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_scann_2fproto_2fcrowding_2eproto::offsets,
    file_level_metadata_scann_2fproto_2fcrowding_2eproto,
    file_level_enum_descriptors_scann_2fproto_2fcrowding_2eproto,
    file_level_service_descriptors_scann_2fproto_2fcrowding_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_scann_2fproto_2fcrowding_2eproto_getter() {
  return &descriptor_table_scann_2fproto_2fcrowding_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_scann_2fproto_2fcrowding_2eproto(&descriptor_table_scann_2fproto_2fcrowding_2eproto);
namespace research_scann {
// ===================================================================

class Crowding_Offline::_Internal {
 public:
  using HasBits = decltype(std::declval<Crowding_Offline>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_._has_bits_);
  static void set_has_per_crowding_attribute_pre_reordering_num_neighbors(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_per_crowding_attribute_post_reordering_num_neighbors(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

Crowding_Offline::Crowding_Offline(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.Crowding.Offline)
}
Crowding_Offline::Crowding_Offline(
    ::google::protobuf::Arena* arena, const Crowding_Offline& from)
    : Crowding_Offline(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Crowding_Offline::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        per_crowding_attribute_pre_reordering_num_neighbors_{2147483647},
        per_crowding_attribute_post_reordering_num_neighbors_{2147483647} {}

inline void Crowding_Offline::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Crowding_Offline::~Crowding_Offline() {
  // @@protoc_insertion_point(destructor:research_scann.Crowding.Offline)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Crowding_Offline::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Crowding_Offline::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.Crowding.Offline)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    _impl_.per_crowding_attribute_pre_reordering_num_neighbors_ = 2147483647;
    _impl_.per_crowding_attribute_post_reordering_num_neighbors_ = 2147483647;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Crowding_Offline::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Crowding_Offline::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Crowding_Offline_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Crowding_Offline, _impl_.per_crowding_attribute_post_reordering_num_neighbors_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_post_reordering_num_neighbors_)}},
    // optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Crowding_Offline, _impl_.per_crowding_attribute_pre_reordering_num_neighbors_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_pre_reordering_num_neighbors_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
    {PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_pre_reordering_num_neighbors_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
    {PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_post_reordering_num_neighbors_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Crowding_Offline::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.Crowding.Offline)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_per_crowding_attribute_pre_reordering_num_neighbors(), target);
  }

  // optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_per_crowding_attribute_post_reordering_num_neighbors(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.Crowding.Offline)
  return target;
}

::size_t Crowding_Offline::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.Crowding.Offline)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int32 per_crowding_attribute_pre_reordering_num_neighbors = 1 [default = 2147483647];
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_per_crowding_attribute_pre_reordering_num_neighbors());
    }

    // optional int32 per_crowding_attribute_post_reordering_num_neighbors = 2 [default = 2147483647];
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_per_crowding_attribute_post_reordering_num_neighbors());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Crowding_Offline::_class_data_ = {
    Crowding_Offline::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Crowding_Offline::GetClassData() const {
  return &_class_data_;
}

void Crowding_Offline::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Crowding_Offline*>(&to_msg);
  auto& from = static_cast<const Crowding_Offline&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.Crowding.Offline)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.per_crowding_attribute_pre_reordering_num_neighbors_ = from._impl_.per_crowding_attribute_pre_reordering_num_neighbors_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.per_crowding_attribute_post_reordering_num_neighbors_ = from._impl_.per_crowding_attribute_post_reordering_num_neighbors_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Crowding_Offline::CopyFrom(const Crowding_Offline& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.Crowding.Offline)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Crowding_Offline::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Crowding_Offline::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Crowding_Offline::InternalSwap(Crowding_Offline* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_post_reordering_num_neighbors_)
      + sizeof(Crowding_Offline::_impl_.per_crowding_attribute_post_reordering_num_neighbors_)
      - PROTOBUF_FIELD_OFFSET(Crowding_Offline, _impl_.per_crowding_attribute_pre_reordering_num_neighbors_)>(
          reinterpret_cast<char*>(&_impl_.per_crowding_attribute_pre_reordering_num_neighbors_),
          reinterpret_cast<char*>(&other->_impl_.per_crowding_attribute_pre_reordering_num_neighbors_));
}

::google::protobuf::Metadata Crowding_Offline::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2fcrowding_2eproto_getter, &descriptor_table_scann_2fproto_2fcrowding_2eproto_once,
      file_level_metadata_scann_2fproto_2fcrowding_2eproto[0]);
}
// ===================================================================

class Crowding::_Internal {
 public:
  using HasBits = decltype(std::declval<Crowding>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Crowding, _impl_._has_bits_);
  static void set_has_enabled(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::research_scann::Crowding_Offline& offline(const Crowding* msg);
  static void set_has_offline(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::research_scann::Crowding_Offline& Crowding::_Internal::offline(const Crowding* msg) {
  return *msg->_impl_.offline_;
}
Crowding::Crowding(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.Crowding)
}
inline PROTOBUF_NDEBUG_INLINE Crowding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Crowding::Crowding(
    ::google::protobuf::Arena* arena,
    const Crowding& from)
    : ::google::protobuf::Message(arena) {
  Crowding* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.offline_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::research_scann::Crowding_Offline>(arena, *from._impl_.offline_)
                : nullptr;
  _impl_.enabled_ = from._impl_.enabled_;

  // @@protoc_insertion_point(copy_constructor:research_scann.Crowding)
}
inline PROTOBUF_NDEBUG_INLINE Crowding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Crowding::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offline_),
           0,
           offsetof(Impl_, enabled_) -
               offsetof(Impl_, offline_) +
               sizeof(Impl_::enabled_));
}
Crowding::~Crowding() {
  // @@protoc_insertion_point(destructor:research_scann.Crowding)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Crowding::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.offline_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Crowding::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.Crowding)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.offline_ != nullptr);
    _impl_.offline_->Clear();
  }
  _impl_.enabled_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Crowding::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Crowding::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Crowding, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Crowding_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional .research_scann.Crowding.Offline offline = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Crowding, _impl_.offline_)}},
    // optional bool enabled = 1 [default = false];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Crowding, _impl_.enabled_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(Crowding, _impl_.enabled_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool enabled = 1 [default = false];
    {PROTOBUF_FIELD_OFFSET(Crowding, _impl_.enabled_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .research_scann.Crowding.Offline offline = 2;
    {PROTOBUF_FIELD_OFFSET(Crowding, _impl_.offline_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::research_scann::Crowding_Offline>()},
  }}, {{
  }},
};

::uint8_t* Crowding::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.Crowding)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bool enabled = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_enabled(), target);
  }

  // optional .research_scann.Crowding.Offline offline = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::offline(this),
        _Internal::offline(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.Crowding)
  return target;
}

::size_t Crowding::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.Crowding)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .research_scann.Crowding.Offline offline = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.offline_);
    }

    // optional bool enabled = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 2;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Crowding::_class_data_ = {
    Crowding::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Crowding::GetClassData() const {
  return &_class_data_;
}

void Crowding::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Crowding*>(&to_msg);
  auto& from = static_cast<const Crowding&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.Crowding)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_offline()->::research_scann::Crowding_Offline::MergeFrom(
          from._internal_offline());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.enabled_ = from._impl_.enabled_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Crowding::CopyFrom(const Crowding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.Crowding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Crowding::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Crowding::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Crowding::InternalSwap(Crowding* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Crowding, _impl_.enabled_)
      + sizeof(Crowding::_impl_.enabled_)
      - PROTOBUF_FIELD_OFFSET(Crowding, _impl_.offline_)>(
          reinterpret_cast<char*>(&_impl_.offline_),
          reinterpret_cast<char*>(&other->_impl_.offline_));
}

::google::protobuf::Metadata Crowding::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2fcrowding_2eproto_getter, &descriptor_table_scann_2fproto_2fcrowding_2eproto_once,
      file_level_metadata_scann_2fproto_2fcrowding_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
