// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/proto/distance_measure.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fdistance_5fmeasure_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fdistance_5fmeasure_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scann_2fproto_2fdistance_5fmeasure_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scann_2fproto_2fdistance_5fmeasure_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scann_2fproto_2fdistance_5fmeasure_2eproto;
namespace research_scann {
class DistanceMeasureConfig;
struct DistanceMeasureConfigDefaultTypeInternal;
extern DistanceMeasureConfigDefaultTypeInternal _DistanceMeasureConfig_default_instance_;
class DistanceMeasureParamsConfig;
struct DistanceMeasureParamsConfigDefaultTypeInternal;
extern DistanceMeasureParamsConfigDefaultTypeInternal _DistanceMeasureParamsConfig_default_instance_;
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace research_scann {

// ===================================================================


// -------------------------------------------------------------------

class DistanceMeasureParamsConfig final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.DistanceMeasureParamsConfig) */ {
 public:
  inline DistanceMeasureParamsConfig() : DistanceMeasureParamsConfig(nullptr) {}
  ~DistanceMeasureParamsConfig() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DistanceMeasureParamsConfig(::google::protobuf::internal::ConstantInitialized);

  inline DistanceMeasureParamsConfig(const DistanceMeasureParamsConfig& from)
      : DistanceMeasureParamsConfig(nullptr, from) {}
  DistanceMeasureParamsConfig(DistanceMeasureParamsConfig&& from) noexcept
    : DistanceMeasureParamsConfig() {
    *this = ::std::move(from);
  }

  inline DistanceMeasureParamsConfig& operator=(const DistanceMeasureParamsConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline DistanceMeasureParamsConfig& operator=(DistanceMeasureParamsConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DistanceMeasureParamsConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const DistanceMeasureParamsConfig* internal_default_instance() {
    return reinterpret_cast<const DistanceMeasureParamsConfig*>(
               &_DistanceMeasureParamsConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DistanceMeasureParamsConfig& a, DistanceMeasureParamsConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(DistanceMeasureParamsConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DistanceMeasureParamsConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DistanceMeasureParamsConfig* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DistanceMeasureParamsConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DistanceMeasureParamsConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DistanceMeasureParamsConfig& from) {
    DistanceMeasureParamsConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DistanceMeasureParamsConfig* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.DistanceMeasureParamsConfig";
  }
  protected:
  explicit DistanceMeasureParamsConfig(::google::protobuf::Arena* arena);
  DistanceMeasureParamsConfig(::google::protobuf::Arena* arena, const DistanceMeasureParamsConfig& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
  };
  // optional string filename = 1;
  bool has_filename() const;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* value);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // @@protoc_insertion_point(class_scope:research_scann.DistanceMeasureParamsConfig)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      59, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fproto_2fdistance_5fmeasure_2eproto;
};// -------------------------------------------------------------------

class DistanceMeasureConfig final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.DistanceMeasureConfig) */ {
 public:
  inline DistanceMeasureConfig() : DistanceMeasureConfig(nullptr) {}
  ~DistanceMeasureConfig() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DistanceMeasureConfig(::google::protobuf::internal::ConstantInitialized);

  inline DistanceMeasureConfig(const DistanceMeasureConfig& from)
      : DistanceMeasureConfig(nullptr, from) {}
  DistanceMeasureConfig(DistanceMeasureConfig&& from) noexcept
    : DistanceMeasureConfig() {
    *this = ::std::move(from);
  }

  inline DistanceMeasureConfig& operator=(const DistanceMeasureConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline DistanceMeasureConfig& operator=(DistanceMeasureConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DistanceMeasureConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const DistanceMeasureConfig* internal_default_instance() {
    return reinterpret_cast<const DistanceMeasureConfig*>(
               &_DistanceMeasureConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DistanceMeasureConfig& a, DistanceMeasureConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(DistanceMeasureConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DistanceMeasureConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DistanceMeasureConfig* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DistanceMeasureConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DistanceMeasureConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DistanceMeasureConfig& from) {
    DistanceMeasureConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DistanceMeasureConfig* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.DistanceMeasureConfig";
  }
  protected:
  explicit DistanceMeasureConfig(::google::protobuf::Arena* arena);
  DistanceMeasureConfig(::google::protobuf::Arena* arena, const DistanceMeasureConfig& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDistanceMeasureFieldNumber = 1,
    kDistanceMeasureParamsFieldNumber = 2,
  };
  // optional string distance_measure = 1 [default = "SquaredL2Distance"];
  bool has_distance_measure() const;
  void clear_distance_measure() ;
  const std::string& distance_measure() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_distance_measure(Arg_&& arg, Args_... args);
  std::string* mutable_distance_measure();
  PROTOBUF_NODISCARD std::string* release_distance_measure();
  void set_allocated_distance_measure(std::string* value);

  private:
  const std::string& _internal_distance_measure() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_distance_measure(
      const std::string& value);
  std::string* _internal_mutable_distance_measure();

  public:
  // optional .research_scann.DistanceMeasureParamsConfig distance_measure_params = 2;
  bool has_distance_measure_params() const;
  void clear_distance_measure_params() ;
  const ::research_scann::DistanceMeasureParamsConfig& distance_measure_params() const;
  PROTOBUF_NODISCARD ::research_scann::DistanceMeasureParamsConfig* release_distance_measure_params();
  ::research_scann::DistanceMeasureParamsConfig* mutable_distance_measure_params();
  void set_allocated_distance_measure_params(::research_scann::DistanceMeasureParamsConfig* value);
  void unsafe_arena_set_allocated_distance_measure_params(::research_scann::DistanceMeasureParamsConfig* value);
  ::research_scann::DistanceMeasureParamsConfig* unsafe_arena_release_distance_measure_params();

  private:
  const ::research_scann::DistanceMeasureParamsConfig& _internal_distance_measure_params() const;
  ::research_scann::DistanceMeasureParamsConfig* _internal_mutable_distance_measure_params();

  public:
  // @@protoc_insertion_point(class_scope:research_scann.DistanceMeasureConfig)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      61, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_distance_measure_;
    ::google::protobuf::internal::ArenaStringPtr distance_measure_;
    ::research_scann::DistanceMeasureParamsConfig* distance_measure_params_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fproto_2fdistance_5fmeasure_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DistanceMeasureConfig

// optional string distance_measure = 1 [default = "SquaredL2Distance"];
inline bool DistanceMeasureConfig::has_distance_measure() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void DistanceMeasureConfig::clear_distance_measure() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.distance_measure_.ClearToDefault(::research_scann::DistanceMeasureConfig::Impl_::_i_give_permission_to_break_this_code_default_distance_measure_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DistanceMeasureConfig::distance_measure() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.DistanceMeasureConfig.distance_measure)
  if (_impl_.distance_measure_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_distance_measure_.get();
  }
  return _internal_distance_measure();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DistanceMeasureConfig::set_distance_measure(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.distance_measure_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:research_scann.DistanceMeasureConfig.distance_measure)
}
inline std::string* DistanceMeasureConfig::mutable_distance_measure() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_distance_measure();
  // @@protoc_insertion_point(field_mutable:research_scann.DistanceMeasureConfig.distance_measure)
  return _s;
}
inline const std::string& DistanceMeasureConfig::_internal_distance_measure() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.distance_measure_.Get();
}
inline void DistanceMeasureConfig::_internal_set_distance_measure(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.distance_measure_.Set(value, GetArena());
}
inline std::string* DistanceMeasureConfig::_internal_mutable_distance_measure() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.distance_measure_.Mutable(::research_scann::DistanceMeasureConfig::Impl_::_i_give_permission_to_break_this_code_default_distance_measure_, GetArena());
}
inline std::string* DistanceMeasureConfig::release_distance_measure() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.DistanceMeasureConfig.distance_measure)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  return _impl_.distance_measure_.Release();
}
inline void DistanceMeasureConfig::set_allocated_distance_measure(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.distance_measure_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:research_scann.DistanceMeasureConfig.distance_measure)
}

// optional .research_scann.DistanceMeasureParamsConfig distance_measure_params = 2;
inline bool DistanceMeasureConfig::has_distance_measure_params() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.distance_measure_params_ != nullptr);
  return value;
}
inline void DistanceMeasureConfig::clear_distance_measure_params() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.distance_measure_params_ != nullptr) _impl_.distance_measure_params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::research_scann::DistanceMeasureParamsConfig& DistanceMeasureConfig::_internal_distance_measure_params() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::research_scann::DistanceMeasureParamsConfig* p = _impl_.distance_measure_params_;
  return p != nullptr ? *p : reinterpret_cast<const ::research_scann::DistanceMeasureParamsConfig&>(::research_scann::_DistanceMeasureParamsConfig_default_instance_);
}
inline const ::research_scann::DistanceMeasureParamsConfig& DistanceMeasureConfig::distance_measure_params() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.DistanceMeasureConfig.distance_measure_params)
  return _internal_distance_measure_params();
}
inline void DistanceMeasureConfig::unsafe_arena_set_allocated_distance_measure_params(::research_scann::DistanceMeasureParamsConfig* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.distance_measure_params_);
  }
  _impl_.distance_measure_params_ = reinterpret_cast<::research_scann::DistanceMeasureParamsConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.DistanceMeasureConfig.distance_measure_params)
}
inline ::research_scann::DistanceMeasureParamsConfig* DistanceMeasureConfig::release_distance_measure_params() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::research_scann::DistanceMeasureParamsConfig* released = _impl_.distance_measure_params_;
  _impl_.distance_measure_params_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::research_scann::DistanceMeasureParamsConfig* DistanceMeasureConfig::unsafe_arena_release_distance_measure_params() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.DistanceMeasureConfig.distance_measure_params)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::research_scann::DistanceMeasureParamsConfig* temp = _impl_.distance_measure_params_;
  _impl_.distance_measure_params_ = nullptr;
  return temp;
}
inline ::research_scann::DistanceMeasureParamsConfig* DistanceMeasureConfig::_internal_mutable_distance_measure_params() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.distance_measure_params_ == nullptr) {
    auto* p = CreateMaybeMessage<::research_scann::DistanceMeasureParamsConfig>(GetArena());
    _impl_.distance_measure_params_ = reinterpret_cast<::research_scann::DistanceMeasureParamsConfig*>(p);
  }
  return _impl_.distance_measure_params_;
}
inline ::research_scann::DistanceMeasureParamsConfig* DistanceMeasureConfig::mutable_distance_measure_params() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::DistanceMeasureParamsConfig* _msg = _internal_mutable_distance_measure_params();
  // @@protoc_insertion_point(field_mutable:research_scann.DistanceMeasureConfig.distance_measure_params)
  return _msg;
}
inline void DistanceMeasureConfig::set_allocated_distance_measure_params(::research_scann::DistanceMeasureParamsConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::research_scann::DistanceMeasureParamsConfig*>(_impl_.distance_measure_params_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::research_scann::DistanceMeasureParamsConfig*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.distance_measure_params_ = reinterpret_cast<::research_scann::DistanceMeasureParamsConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:research_scann.DistanceMeasureConfig.distance_measure_params)
}

// -------------------------------------------------------------------

// DistanceMeasureParamsConfig

// optional string filename = 1;
inline bool DistanceMeasureParamsConfig::has_filename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void DistanceMeasureParamsConfig::clear_filename() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.filename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DistanceMeasureParamsConfig::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.DistanceMeasureParamsConfig.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DistanceMeasureParamsConfig::set_filename(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:research_scann.DistanceMeasureParamsConfig.filename)
}
inline std::string* DistanceMeasureParamsConfig::mutable_filename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:research_scann.DistanceMeasureParamsConfig.filename)
  return _s;
}
inline const std::string& DistanceMeasureParamsConfig::_internal_filename() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.filename_.Get();
}
inline void DistanceMeasureParamsConfig::_internal_set_filename(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(value, GetArena());
}
inline std::string* DistanceMeasureParamsConfig::_internal_mutable_filename() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filename_.Mutable( GetArena());
}
inline std::string* DistanceMeasureParamsConfig::release_filename() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.DistanceMeasureParamsConfig.filename)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.filename_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filename_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void DistanceMeasureParamsConfig::set_allocated_filename(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.filename_.IsDefault()) {
          _impl_.filename_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:research_scann.DistanceMeasureParamsConfig.filename)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_scann_2fproto_2fdistance_5fmeasure_2eproto_2epb_2eh
