// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/proto/restricts.proto

#include "scann/proto/restricts.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace research_scann {

inline constexpr V3RestrictsConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        empty_namespace_matching_mode_{static_cast< ::research_scann::V3RestrictsConfig_EmptyNamespaceMatchingMode >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR V3RestrictsConfig::V3RestrictsConfig(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct V3RestrictsConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR V3RestrictsConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~V3RestrictsConfigDefaultTypeInternal() {}
  union {
    V3RestrictsConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 V3RestrictsConfigDefaultTypeInternal _V3RestrictsConfig_default_instance_;

inline constexpr TokenNamespace::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uint64_tokens_{},
        string_tokens_{},
        uint64_blacklist_tokens_{},
        string_blacklist_tokens_{},
        namespace__(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR TokenNamespace::TokenNamespace(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TokenNamespaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokenNamespaceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokenNamespaceDefaultTypeInternal() {}
  union {
    TokenNamespace _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokenNamespaceDefaultTypeInternal _TokenNamespace_default_instance_;

inline constexpr V3Restrict::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : namespaces_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR V3Restrict::V3Restrict(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct V3RestrictDefaultTypeInternal {
  PROTOBUF_CONSTEXPR V3RestrictDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~V3RestrictDefaultTypeInternal() {}
  union {
    V3Restrict _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 V3RestrictDefaultTypeInternal _V3Restrict_default_instance_;

inline constexpr RestrictsConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        v3_restricts_{nullptr},
        enabled_{false},
        restrict_cache_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RestrictsConfig::RestrictsConfig(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RestrictsConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RestrictsConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RestrictsConfigDefaultTypeInternal() {}
  union {
    RestrictsConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RestrictsConfigDefaultTypeInternal _RestrictsConfig_default_instance_;
}  // namespace research_scann
static ::_pb::Metadata file_level_metadata_scann_2fproto_2frestricts_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_scann_2fproto_2frestricts_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_scann_2fproto_2frestricts_2eproto = nullptr;
const ::uint32_t TableStruct_scann_2fproto_2frestricts_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::research_scann::V3Restrict, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::V3Restrict, _impl_.namespaces_),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_.namespace__),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_.string_tokens_),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_.uint64_tokens_),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_.string_blacklist_tokens_),
    PROTOBUF_FIELD_OFFSET(::research_scann::TokenNamespace, _impl_.uint64_blacklist_tokens_),
    0,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::research_scann::RestrictsConfig, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::RestrictsConfig, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::RestrictsConfig, _impl_.enabled_),
    PROTOBUF_FIELD_OFFSET(::research_scann::RestrictsConfig, _impl_.restrict_cache_size_),
    PROTOBUF_FIELD_OFFSET(::research_scann::RestrictsConfig, _impl_.v3_restricts_),
    1,
    2,
    0,
    PROTOBUF_FIELD_OFFSET(::research_scann::V3RestrictsConfig, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::research_scann::V3RestrictsConfig, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::research_scann::V3RestrictsConfig, _impl_.empty_namespace_matching_mode_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::research_scann::V3Restrict)},
        {9, 22, -1, sizeof(::research_scann::TokenNamespace)},
        {27, 38, -1, sizeof(::research_scann::RestrictsConfig)},
        {41, 50, -1, sizeof(::research_scann::V3RestrictsConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::research_scann::_V3Restrict_default_instance_._instance,
    &::research_scann::_TokenNamespace_default_instance_._instance,
    &::research_scann::_RestrictsConfig_default_instance_._instance,
    &::research_scann::_V3RestrictsConfig_default_instance_._instance,
};
const char descriptor_table_protodef_scann_2fproto_2frestricts_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\033scann/proto/restricts.proto\022\016research_"
    "scann\"@\n\nV3Restrict\0222\n\nnamespaces\030\001 \003(\0132"
    "\036.research_scann.TokenNamespace\"\233\001\n\016Toke"
    "nNamespace\022\021\n\tnamespace\030\001 \001(\t\022\025\n\rstring_"
    "tokens\030\003 \003(\t\022\031\n\ruint64_tokens\030\002 \003(\006B\002\020\001\022"
    "\037\n\027string_blacklist_tokens\030\005 \003(\t\022#\n\027uint"
    "64_blacklist_tokens\030\004 \003(\006B\002\020\001\"\202\001\n\017Restri"
    "ctsConfig\022\026\n\007enabled\030\001 \001(\010:\005false\022\036\n\023res"
    "trict_cache_size\030\002 \001(\005:\0010\0227\n\014v3_restrict"
    "s\030\003 \001(\0132!.research_scann.V3RestrictsConf"
    "ig\"\201\002\n\021V3RestrictsConfig\022p\n\035empty_namesp"
    "ace_matching_mode\030\001 \001(\0162<.research_scann"
    ".V3RestrictsConfig.EmptyNamespaceMatchin"
    "gMode:\013UNSPECIFIED\"z\n\032EmptyNamespaceMatc"
    "hingMode\022\017\n\013UNSPECIFIED\020\000\022\020\n\014FORWARD_MOD"
    "E\020\001\022\020\n\014REVERSE_MODE\020\002\022\021\n\rLAX_SYMMETRIC\020\003"
    "\022\024\n\020STRICT_SYMMETRIC\020\004B\003\370\001\001"
};
static ::absl::once_flag descriptor_table_scann_2fproto_2frestricts_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_scann_2fproto_2frestricts_2eproto = {
    false,
    false,
    667,
    descriptor_table_protodef_scann_2fproto_2frestricts_2eproto,
    "scann/proto/restricts.proto",
    &descriptor_table_scann_2fproto_2frestricts_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_scann_2fproto_2frestricts_2eproto::offsets,
    file_level_metadata_scann_2fproto_2frestricts_2eproto,
    file_level_enum_descriptors_scann_2fproto_2frestricts_2eproto,
    file_level_service_descriptors_scann_2fproto_2frestricts_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_scann_2fproto_2frestricts_2eproto_getter() {
  return &descriptor_table_scann_2fproto_2frestricts_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_scann_2fproto_2frestricts_2eproto(&descriptor_table_scann_2fproto_2frestricts_2eproto);
namespace research_scann {
const ::google::protobuf::EnumDescriptor* V3RestrictsConfig_EmptyNamespaceMatchingMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_scann_2fproto_2frestricts_2eproto);
  return file_level_enum_descriptors_scann_2fproto_2frestricts_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t V3RestrictsConfig_EmptyNamespaceMatchingMode_internal_data_[] = {
    327680u, 0u, };
bool V3RestrictsConfig_EmptyNamespaceMatchingMode_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::UNSPECIFIED;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::FORWARD_MODE;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::REVERSE_MODE;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::LAX_SYMMETRIC;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::STRICT_SYMMETRIC;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::EmptyNamespaceMatchingMode_MIN;
constexpr V3RestrictsConfig_EmptyNamespaceMatchingMode V3RestrictsConfig::EmptyNamespaceMatchingMode_MAX;
constexpr int V3RestrictsConfig::EmptyNamespaceMatchingMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class V3Restrict::_Internal {
 public:
};

V3Restrict::V3Restrict(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.V3Restrict)
}
inline PROTOBUF_NDEBUG_INLINE V3Restrict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : namespaces_{visibility, arena, from.namespaces_},
        _cached_size_{0} {}

V3Restrict::V3Restrict(
    ::google::protobuf::Arena* arena,
    const V3Restrict& from)
    : ::google::protobuf::Message(arena) {
  V3Restrict* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:research_scann.V3Restrict)
}
inline PROTOBUF_NDEBUG_INLINE V3Restrict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : namespaces_{visibility, arena},
        _cached_size_{0} {}

inline void V3Restrict::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
V3Restrict::~V3Restrict() {
  // @@protoc_insertion_point(destructor:research_scann.V3Restrict)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void V3Restrict::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void V3Restrict::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.V3Restrict)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.namespaces_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* V3Restrict::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> V3Restrict::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_V3Restrict_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .research_scann.TokenNamespace namespaces = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(V3Restrict, _impl_.namespaces_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .research_scann.TokenNamespace namespaces = 1;
    {PROTOBUF_FIELD_OFFSET(V3Restrict, _impl_.namespaces_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::research_scann::TokenNamespace>()},
  }}, {{
  }},
};

::uint8_t* V3Restrict::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.V3Restrict)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .research_scann.TokenNamespace namespaces = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_namespaces_size()); i < n; i++) {
    const auto& repfield = this->_internal_namespaces().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.V3Restrict)
  return target;
}

::size_t V3Restrict::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.V3Restrict)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .research_scann.TokenNamespace namespaces = 1;
  total_size += 1UL * this->_internal_namespaces_size();
  for (const auto& msg : this->_internal_namespaces()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData V3Restrict::_class_data_ = {
    V3Restrict::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* V3Restrict::GetClassData() const {
  return &_class_data_;
}

void V3Restrict::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<V3Restrict*>(&to_msg);
  auto& from = static_cast<const V3Restrict&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.V3Restrict)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_namespaces()->MergeFrom(
      from._internal_namespaces());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void V3Restrict::CopyFrom(const V3Restrict& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.V3Restrict)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool V3Restrict::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* V3Restrict::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void V3Restrict::InternalSwap(V3Restrict* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.namespaces_.InternalSwap(&other->_impl_.namespaces_);
}

::google::protobuf::Metadata V3Restrict::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2frestricts_2eproto_getter, &descriptor_table_scann_2fproto_2frestricts_2eproto_once,
      file_level_metadata_scann_2fproto_2frestricts_2eproto[0]);
}
// ===================================================================

class TokenNamespace::_Internal {
 public:
  using HasBits = decltype(std::declval<TokenNamespace>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_._has_bits_);
  static void set_has_namespace_(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TokenNamespace::TokenNamespace(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.TokenNamespace)
}
inline PROTOBUF_NDEBUG_INLINE TokenNamespace::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uint64_tokens_{visibility, arena, from.uint64_tokens_},
        string_tokens_{visibility, arena, from.string_tokens_},
        uint64_blacklist_tokens_{visibility, arena, from.uint64_blacklist_tokens_},
        string_blacklist_tokens_{visibility, arena, from.string_blacklist_tokens_},
        namespace__(arena, from.namespace__) {}

TokenNamespace::TokenNamespace(
    ::google::protobuf::Arena* arena,
    const TokenNamespace& from)
    : ::google::protobuf::Message(arena) {
  TokenNamespace* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:research_scann.TokenNamespace)
}
inline PROTOBUF_NDEBUG_INLINE TokenNamespace::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        uint64_tokens_{visibility, arena},
        string_tokens_{visibility, arena},
        uint64_blacklist_tokens_{visibility, arena},
        string_blacklist_tokens_{visibility, arena},
        namespace__(arena) {}

inline void TokenNamespace::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TokenNamespace::~TokenNamespace() {
  // @@protoc_insertion_point(destructor:research_scann.TokenNamespace)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TokenNamespace::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.namespace__.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TokenNamespace::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.TokenNamespace)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uint64_tokens_.Clear();
  _impl_.string_tokens_.Clear();
  _impl_.uint64_blacklist_tokens_.Clear();
  _impl_.string_blacklist_tokens_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.namespace__.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TokenNamespace::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 83, 2> TokenNamespace::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TokenNamespace_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string namespace = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.namespace__)}},
    // repeated fixed64 uint64_tokens = 2 [packed = true];
    {::_pbi::TcParser::FastF64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.uint64_tokens_)}},
    // repeated string string_tokens = 3;
    {::_pbi::TcParser::FastSR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.string_tokens_)}},
    // repeated fixed64 uint64_blacklist_tokens = 4 [packed = true];
    {::_pbi::TcParser::FastF64P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.uint64_blacklist_tokens_)}},
    // repeated string string_blacklist_tokens = 5;
    {::_pbi::TcParser::FastSR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.string_blacklist_tokens_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string namespace = 1;
    {PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.namespace__), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated fixed64 uint64_tokens = 2 [packed = true];
    {PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.uint64_tokens_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFixed64)},
    // repeated string string_tokens = 3;
    {PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.string_tokens_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
    // repeated fixed64 uint64_blacklist_tokens = 4 [packed = true];
    {PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.uint64_blacklist_tokens_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFixed64)},
    // repeated string string_blacklist_tokens = 5;
    {PROTOBUF_FIELD_OFFSET(TokenNamespace, _impl_.string_blacklist_tokens_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\35\11\0\15\0\27\0\0"
    "research_scann.TokenNamespace"
    "namespace"
    "string_tokens"
    "string_blacklist_tokens"
  }},
};

::uint8_t* TokenNamespace::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.TokenNamespace)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string namespace = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_namespace_();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "research_scann.TokenNamespace.namespace");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated fixed64 uint64_tokens = 2 [packed = true];
  if (this->_internal_uint64_tokens_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_uint64_tokens(), target);
  }

  // repeated string string_tokens = 3;
  for (int i = 0, n = this->_internal_string_tokens_size(); i < n; ++i) {
    const auto& s = this->_internal_string_tokens().Get(i);
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "research_scann.TokenNamespace.string_tokens");
    target = stream->WriteString(3, s, target);
  }

  // repeated fixed64 uint64_blacklist_tokens = 4 [packed = true];
  if (this->_internal_uint64_blacklist_tokens_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_uint64_blacklist_tokens(), target);
  }

  // repeated string string_blacklist_tokens = 5;
  for (int i = 0, n = this->_internal_string_blacklist_tokens_size(); i < n; ++i) {
    const auto& s = this->_internal_string_blacklist_tokens().Get(i);
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "research_scann.TokenNamespace.string_blacklist_tokens");
    target = stream->WriteString(5, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.TokenNamespace)
  return target;
}

::size_t TokenNamespace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.TokenNamespace)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated fixed64 uint64_tokens = 2 [packed = true];
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_uint64_tokens_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated string string_tokens = 3;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_string_tokens().size());
  for (int i = 0, n = _internal_string_tokens().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_string_tokens().Get(i));
  }
  // repeated fixed64 uint64_blacklist_tokens = 4 [packed = true];
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_uint64_blacklist_tokens_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated string string_blacklist_tokens = 5;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_string_blacklist_tokens().size());
  for (int i = 0, n = _internal_string_blacklist_tokens().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_string_blacklist_tokens().Get(i));
  }
  // optional string namespace = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_namespace_());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TokenNamespace::_class_data_ = {
    TokenNamespace::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TokenNamespace::GetClassData() const {
  return &_class_data_;
}

void TokenNamespace::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TokenNamespace*>(&to_msg);
  auto& from = static_cast<const TokenNamespace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.TokenNamespace)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_uint64_tokens()->MergeFrom(from._internal_uint64_tokens());
  _this->_internal_mutable_string_tokens()->MergeFrom(from._internal_string_tokens());
  _this->_internal_mutable_uint64_blacklist_tokens()->MergeFrom(from._internal_uint64_blacklist_tokens());
  _this->_internal_mutable_string_blacklist_tokens()->MergeFrom(from._internal_string_blacklist_tokens());
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_namespace_(from._internal_namespace_());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TokenNamespace::CopyFrom(const TokenNamespace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.TokenNamespace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TokenNamespace::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TokenNamespace::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TokenNamespace::InternalSwap(TokenNamespace* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.uint64_tokens_.InternalSwap(&other->_impl_.uint64_tokens_);
  _impl_.string_tokens_.InternalSwap(&other->_impl_.string_tokens_);
  _impl_.uint64_blacklist_tokens_.InternalSwap(&other->_impl_.uint64_blacklist_tokens_);
  _impl_.string_blacklist_tokens_.InternalSwap(&other->_impl_.string_blacklist_tokens_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.namespace__, &other->_impl_.namespace__, arena);
}

::google::protobuf::Metadata TokenNamespace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2frestricts_2eproto_getter, &descriptor_table_scann_2fproto_2frestricts_2eproto_once,
      file_level_metadata_scann_2fproto_2frestricts_2eproto[1]);
}
// ===================================================================

class RestrictsConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<RestrictsConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_._has_bits_);
  static void set_has_enabled(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_restrict_cache_size(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::research_scann::V3RestrictsConfig& v3_restricts(const RestrictsConfig* msg);
  static void set_has_v3_restricts(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::research_scann::V3RestrictsConfig& RestrictsConfig::_Internal::v3_restricts(const RestrictsConfig* msg) {
  return *msg->_impl_.v3_restricts_;
}
RestrictsConfig::RestrictsConfig(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.RestrictsConfig)
}
inline PROTOBUF_NDEBUG_INLINE RestrictsConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

RestrictsConfig::RestrictsConfig(
    ::google::protobuf::Arena* arena,
    const RestrictsConfig& from)
    : ::google::protobuf::Message(arena) {
  RestrictsConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.v3_restricts_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::research_scann::V3RestrictsConfig>(arena, *from._impl_.v3_restricts_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, enabled_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, enabled_),
           offsetof(Impl_, restrict_cache_size_) -
               offsetof(Impl_, enabled_) +
               sizeof(Impl_::restrict_cache_size_));

  // @@protoc_insertion_point(copy_constructor:research_scann.RestrictsConfig)
}
inline PROTOBUF_NDEBUG_INLINE RestrictsConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RestrictsConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, v3_restricts_),
           0,
           offsetof(Impl_, restrict_cache_size_) -
               offsetof(Impl_, v3_restricts_) +
               sizeof(Impl_::restrict_cache_size_));
}
RestrictsConfig::~RestrictsConfig() {
  // @@protoc_insertion_point(destructor:research_scann.RestrictsConfig)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RestrictsConfig::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.v3_restricts_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RestrictsConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.RestrictsConfig)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.v3_restricts_ != nullptr);
    _impl_.v3_restricts_->Clear();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.enabled_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.restrict_cache_size_) -
        reinterpret_cast<char*>(&_impl_.enabled_)) + sizeof(_impl_.restrict_cache_size_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RestrictsConfig::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> RestrictsConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RestrictsConfig_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bool enabled = 1 [default = false];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RestrictsConfig, _impl_.enabled_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.enabled_)}},
    // optional int32 restrict_cache_size = 2 [default = 0];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RestrictsConfig, _impl_.restrict_cache_size_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.restrict_cache_size_)}},
    // optional .research_scann.V3RestrictsConfig v3_restricts = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.v3_restricts_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool enabled = 1 [default = false];
    {PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.enabled_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 restrict_cache_size = 2 [default = 0];
    {PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.restrict_cache_size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .research_scann.V3RestrictsConfig v3_restricts = 3;
    {PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.v3_restricts_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::research_scann::V3RestrictsConfig>()},
  }}, {{
  }},
};

::uint8_t* RestrictsConfig::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.RestrictsConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bool enabled = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_enabled(), target);
  }

  // optional int32 restrict_cache_size = 2 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_restrict_cache_size(), target);
  }

  // optional .research_scann.V3RestrictsConfig v3_restricts = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::v3_restricts(this),
        _Internal::v3_restricts(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.RestrictsConfig)
  return target;
}

::size_t RestrictsConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.RestrictsConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .research_scann.V3RestrictsConfig v3_restricts = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v3_restricts_);
    }

    // optional bool enabled = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 2;
    }

    // optional int32 restrict_cache_size = 2 [default = 0];
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_restrict_cache_size());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RestrictsConfig::_class_data_ = {
    RestrictsConfig::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RestrictsConfig::GetClassData() const {
  return &_class_data_;
}

void RestrictsConfig::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RestrictsConfig*>(&to_msg);
  auto& from = static_cast<const RestrictsConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.RestrictsConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_v3_restricts()->::research_scann::V3RestrictsConfig::MergeFrom(
          from._internal_v3_restricts());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.enabled_ = from._impl_.enabled_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.restrict_cache_size_ = from._impl_.restrict_cache_size_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RestrictsConfig::CopyFrom(const RestrictsConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.RestrictsConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RestrictsConfig::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RestrictsConfig::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RestrictsConfig::InternalSwap(RestrictsConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.restrict_cache_size_)
      + sizeof(RestrictsConfig::_impl_.restrict_cache_size_)
      - PROTOBUF_FIELD_OFFSET(RestrictsConfig, _impl_.v3_restricts_)>(
          reinterpret_cast<char*>(&_impl_.v3_restricts_),
          reinterpret_cast<char*>(&other->_impl_.v3_restricts_));
}

::google::protobuf::Metadata RestrictsConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2frestricts_2eproto_getter, &descriptor_table_scann_2fproto_2frestricts_2eproto_once,
      file_level_metadata_scann_2fproto_2frestricts_2eproto[2]);
}
// ===================================================================

class V3RestrictsConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<V3RestrictsConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(V3RestrictsConfig, _impl_._has_bits_);
  static void set_has_empty_namespace_matching_mode(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

V3RestrictsConfig::V3RestrictsConfig(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:research_scann.V3RestrictsConfig)
}
V3RestrictsConfig::V3RestrictsConfig(
    ::google::protobuf::Arena* arena, const V3RestrictsConfig& from)
    : V3RestrictsConfig(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE V3RestrictsConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void V3RestrictsConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.empty_namespace_matching_mode_ = {};
}
V3RestrictsConfig::~V3RestrictsConfig() {
  // @@protoc_insertion_point(destructor:research_scann.V3RestrictsConfig)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void V3RestrictsConfig::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void V3RestrictsConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.V3RestrictsConfig)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.empty_namespace_matching_mode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* V3RestrictsConfig::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> V3RestrictsConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(V3RestrictsConfig, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_V3RestrictsConfig_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional .research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode empty_namespace_matching_mode = 1 [default = UNSPECIFIED];
    {::_pbi::TcParser::FastEr0S1,
     {8, 0, 4, PROTOBUF_FIELD_OFFSET(V3RestrictsConfig, _impl_.empty_namespace_matching_mode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode empty_namespace_matching_mode = 1 [default = UNSPECIFIED];
    {PROTOBUF_FIELD_OFFSET(V3RestrictsConfig, _impl_.empty_namespace_matching_mode_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }}, {{
    {0, 5},
  }}, {{
  }},
};

::uint8_t* V3RestrictsConfig::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.V3RestrictsConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode empty_namespace_matching_mode = 1 [default = UNSPECIFIED];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_empty_namespace_matching_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.V3RestrictsConfig)
  return target;
}

::size_t V3RestrictsConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.V3RestrictsConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode empty_namespace_matching_mode = 1 [default = UNSPECIFIED];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_empty_namespace_matching_mode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData V3RestrictsConfig::_class_data_ = {
    V3RestrictsConfig::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* V3RestrictsConfig::GetClassData() const {
  return &_class_data_;
}

void V3RestrictsConfig::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<V3RestrictsConfig*>(&to_msg);
  auto& from = static_cast<const V3RestrictsConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:research_scann.V3RestrictsConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_empty_namespace_matching_mode(from._internal_empty_namespace_matching_mode());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void V3RestrictsConfig::CopyFrom(const V3RestrictsConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.V3RestrictsConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool V3RestrictsConfig::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* V3RestrictsConfig::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void V3RestrictsConfig::InternalSwap(V3RestrictsConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.empty_namespace_matching_mode_, other->_impl_.empty_namespace_matching_mode_);
}

::google::protobuf::Metadata V3RestrictsConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scann_2fproto_2frestricts_2eproto_getter, &descriptor_table_scann_2fproto_2frestricts_2eproto_once,
      file_level_metadata_scann_2fproto_2frestricts_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
