// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/scann_ops/scann_assets.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_scann_2fscann_5fops_2fscann_5fassets_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_scann_2fscann_5fops_2fscann_5fassets_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scann_2fscann_5fops_2fscann_5fassets_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scann_2fscann_5fops_2fscann_5fassets_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scann_2fscann_5fops_2fscann_5fassets_2eproto;
namespace research_scann {
class ScannAsset;
struct ScannAssetDefaultTypeInternal;
extern ScannAssetDefaultTypeInternal _ScannAsset_default_instance_;
class ScannAssets;
struct ScannAssetsDefaultTypeInternal;
extern ScannAssetsDefaultTypeInternal _ScannAssets_default_instance_;
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace research_scann {
enum ScannAsset_AssetType : int {
  ScannAsset_AssetType_UNSPECIFIED_TYPE = 0,
  ScannAsset_AssetType_DATASET = 1,
  ScannAsset_AssetType_INT8_DATASET = 2,
  ScannAsset_AssetType_AH_DATASET = 3,
  ScannAsset_AssetType_TOKENIZATION = 4,
  ScannAsset_AssetType_REORDERING_INT8_MULTIPLIERS = 5,
  ScannAsset_AssetType_BRUTE_FORCE_INT8_MULTIPLIERS = 6,
  ScannAsset_AssetType_AH_CENTERS = 7,
  ScannAsset_AssetType_PARTITIONER = 8,
  ScannAsset_AssetType_DATASET_NPY = 9,
  ScannAsset_AssetType_INT8_DATASET_NPY = 10,
  ScannAsset_AssetType_AH_DATASET_NPY = 11,
  ScannAsset_AssetType_TOKENIZATION_NPY = 12,
  ScannAsset_AssetType_INT8_MULTIPLIERS_NPY = 13,
  ScannAsset_AssetType_INT8_NORMS_NPY = 14,
};

bool ScannAsset_AssetType_IsValid(int value);
extern const uint32_t ScannAsset_AssetType_internal_data_[];
constexpr ScannAsset_AssetType ScannAsset_AssetType_AssetType_MIN = static_cast<ScannAsset_AssetType>(0);
constexpr ScannAsset_AssetType ScannAsset_AssetType_AssetType_MAX = static_cast<ScannAsset_AssetType>(14);
constexpr int ScannAsset_AssetType_AssetType_ARRAYSIZE = 14 + 1;
const ::google::protobuf::EnumDescriptor*
ScannAsset_AssetType_descriptor();
template <typename T>
const std::string& ScannAsset_AssetType_Name(T value) {
  static_assert(std::is_same<T, ScannAsset_AssetType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AssetType_Name().");
  return ScannAsset_AssetType_Name(static_cast<ScannAsset_AssetType>(value));
}
template <>
inline const std::string& ScannAsset_AssetType_Name(ScannAsset_AssetType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ScannAsset_AssetType_descriptor,
                                                 0, 14>(
      static_cast<int>(value));
}
inline bool ScannAsset_AssetType_Parse(absl::string_view name, ScannAsset_AssetType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ScannAsset_AssetType>(
      ScannAsset_AssetType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ScannAsset final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.ScannAsset) */ {
 public:
  inline ScannAsset() : ScannAsset(nullptr) {}
  ~ScannAsset() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ScannAsset(::google::protobuf::internal::ConstantInitialized);

  inline ScannAsset(const ScannAsset& from)
      : ScannAsset(nullptr, from) {}
  ScannAsset(ScannAsset&& from) noexcept
    : ScannAsset() {
    *this = ::std::move(from);
  }

  inline ScannAsset& operator=(const ScannAsset& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScannAsset& operator=(ScannAsset&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScannAsset& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScannAsset* internal_default_instance() {
    return reinterpret_cast<const ScannAsset*>(
               &_ScannAsset_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ScannAsset& a, ScannAsset& b) {
    a.Swap(&b);
  }
  inline void Swap(ScannAsset* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScannAsset* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScannAsset* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScannAsset>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScannAsset& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ScannAsset& from) {
    ScannAsset::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ScannAsset* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.ScannAsset";
  }
  protected:
  explicit ScannAsset(::google::protobuf::Arena* arena);
  ScannAsset(::google::protobuf::Arena* arena, const ScannAsset& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using AssetType = ScannAsset_AssetType;
  static constexpr AssetType UNSPECIFIED_TYPE = ScannAsset_AssetType_UNSPECIFIED_TYPE;
  static constexpr AssetType DATASET = ScannAsset_AssetType_DATASET;
  static constexpr AssetType INT8_DATASET = ScannAsset_AssetType_INT8_DATASET;
  static constexpr AssetType AH_DATASET = ScannAsset_AssetType_AH_DATASET;
  static constexpr AssetType TOKENIZATION = ScannAsset_AssetType_TOKENIZATION;
  static constexpr AssetType REORDERING_INT8_MULTIPLIERS = ScannAsset_AssetType_REORDERING_INT8_MULTIPLIERS;
  static constexpr AssetType BRUTE_FORCE_INT8_MULTIPLIERS = ScannAsset_AssetType_BRUTE_FORCE_INT8_MULTIPLIERS;
  static constexpr AssetType AH_CENTERS = ScannAsset_AssetType_AH_CENTERS;
  static constexpr AssetType PARTITIONER = ScannAsset_AssetType_PARTITIONER;
  static constexpr AssetType DATASET_NPY = ScannAsset_AssetType_DATASET_NPY;
  static constexpr AssetType INT8_DATASET_NPY = ScannAsset_AssetType_INT8_DATASET_NPY;
  static constexpr AssetType AH_DATASET_NPY = ScannAsset_AssetType_AH_DATASET_NPY;
  static constexpr AssetType TOKENIZATION_NPY = ScannAsset_AssetType_TOKENIZATION_NPY;
  static constexpr AssetType INT8_MULTIPLIERS_NPY = ScannAsset_AssetType_INT8_MULTIPLIERS_NPY;
  static constexpr AssetType INT8_NORMS_NPY = ScannAsset_AssetType_INT8_NORMS_NPY;
  static inline bool AssetType_IsValid(int value) {
    return ScannAsset_AssetType_IsValid(value);
  }
  static constexpr AssetType AssetType_MIN = ScannAsset_AssetType_AssetType_MIN;
  static constexpr AssetType AssetType_MAX = ScannAsset_AssetType_AssetType_MAX;
  static constexpr int AssetType_ARRAYSIZE = ScannAsset_AssetType_AssetType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* AssetType_descriptor() {
    return ScannAsset_AssetType_descriptor();
  }
  template <typename T>
  static inline const std::string& AssetType_Name(T value) {
    return ScannAsset_AssetType_Name(value);
  }
  static inline bool AssetType_Parse(absl::string_view name, AssetType* value) {
    return ScannAsset_AssetType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kAssetPathFieldNumber = 2,
    kAssetTypeFieldNumber = 1,
  };
  // optional string asset_path = 2;
  bool has_asset_path() const;
  void clear_asset_path() ;
  const std::string& asset_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset_path(Arg_&& arg, Args_... args);
  std::string* mutable_asset_path();
  PROTOBUF_NODISCARD std::string* release_asset_path();
  void set_allocated_asset_path(std::string* value);

  private:
  const std::string& _internal_asset_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset_path(
      const std::string& value);
  std::string* _internal_mutable_asset_path();

  public:
  // optional .research_scann.ScannAsset.AssetType asset_type = 1;
  bool has_asset_type() const;
  void clear_asset_type() ;
  ::research_scann::ScannAsset_AssetType asset_type() const;
  void set_asset_type(::research_scann::ScannAsset_AssetType value);

  private:
  ::research_scann::ScannAsset_AssetType _internal_asset_type() const;
  void _internal_set_asset_type(::research_scann::ScannAsset_AssetType value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.ScannAsset)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      44, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr asset_path_;
    int asset_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fscann_5fops_2fscann_5fassets_2eproto;
};// -------------------------------------------------------------------

class ScannAssets final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.ScannAssets) */ {
 public:
  inline ScannAssets() : ScannAssets(nullptr) {}
  ~ScannAssets() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ScannAssets(::google::protobuf::internal::ConstantInitialized);

  inline ScannAssets(const ScannAssets& from)
      : ScannAssets(nullptr, from) {}
  ScannAssets(ScannAssets&& from) noexcept
    : ScannAssets() {
    *this = ::std::move(from);
  }

  inline ScannAssets& operator=(const ScannAssets& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScannAssets& operator=(ScannAssets&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScannAssets& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScannAssets* internal_default_instance() {
    return reinterpret_cast<const ScannAssets*>(
               &_ScannAssets_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ScannAssets& a, ScannAssets& b) {
    a.Swap(&b);
  }
  inline void Swap(ScannAssets* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScannAssets* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScannAssets* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScannAssets>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScannAssets& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ScannAssets& from) {
    ScannAssets::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ScannAssets* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.ScannAssets";
  }
  protected:
  explicit ScannAssets(::google::protobuf::Arena* arena);
  ScannAssets(::google::protobuf::Arena* arena, const ScannAssets& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAssetsFieldNumber = 1,
    kTrainedOnTheFlyFieldNumber = 2,
  };
  // repeated .research_scann.ScannAsset assets = 1;
  int assets_size() const;
  private:
  int _internal_assets_size() const;

  public:
  void clear_assets() ;
  ::research_scann::ScannAsset* mutable_assets(int index);
  ::google::protobuf::RepeatedPtrField< ::research_scann::ScannAsset >*
      mutable_assets();
  private:
  const ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>& _internal_assets() const;
  ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>* _internal_mutable_assets();
  public:
  const ::research_scann::ScannAsset& assets(int index) const;
  ::research_scann::ScannAsset* add_assets();
  const ::google::protobuf::RepeatedPtrField< ::research_scann::ScannAsset >&
      assets() const;
  // optional bool trained_on_the_fly = 2 [default = true];
  bool has_trained_on_the_fly() const;
  void clear_trained_on_the_fly() ;
  bool trained_on_the_fly() const;
  void set_trained_on_the_fly(bool value);

  private:
  bool _internal_trained_on_the_fly() const;
  void _internal_set_trained_on_the_fly(bool value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.ScannAssets)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::research_scann::ScannAsset > assets_;
    bool trained_on_the_fly_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fscann_5fops_2fscann_5fassets_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ScannAsset

// optional .research_scann.ScannAsset.AssetType asset_type = 1;
inline bool ScannAsset::has_asset_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ScannAsset::clear_asset_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.asset_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::research_scann::ScannAsset_AssetType ScannAsset::asset_type() const {
  // @@protoc_insertion_point(field_get:research_scann.ScannAsset.asset_type)
  return _internal_asset_type();
}
inline void ScannAsset::set_asset_type(::research_scann::ScannAsset_AssetType value) {
  _internal_set_asset_type(value);
  // @@protoc_insertion_point(field_set:research_scann.ScannAsset.asset_type)
}
inline ::research_scann::ScannAsset_AssetType ScannAsset::_internal_asset_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::research_scann::ScannAsset_AssetType>(_impl_.asset_type_);
}
inline void ScannAsset::_internal_set_asset_type(::research_scann::ScannAsset_AssetType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::research_scann::ScannAsset_AssetType_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.asset_type_ = value;
}

// optional string asset_path = 2;
inline bool ScannAsset::has_asset_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScannAsset::clear_asset_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.asset_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ScannAsset::asset_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.ScannAsset.asset_path)
  return _internal_asset_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannAsset::set_asset_path(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.asset_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:research_scann.ScannAsset.asset_path)
}
inline std::string* ScannAsset::mutable_asset_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset_path();
  // @@protoc_insertion_point(field_mutable:research_scann.ScannAsset.asset_path)
  return _s;
}
inline const std::string& ScannAsset::_internal_asset_path() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.asset_path_.Get();
}
inline void ScannAsset::_internal_set_asset_path(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.asset_path_.Set(value, GetArena());
}
inline std::string* ScannAsset::_internal_mutable_asset_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.asset_path_.Mutable( GetArena());
}
inline std::string* ScannAsset::release_asset_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.ScannAsset.asset_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.asset_path_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.asset_path_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ScannAsset::set_allocated_asset_path(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.asset_path_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.asset_path_.IsDefault()) {
          _impl_.asset_path_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:research_scann.ScannAsset.asset_path)
}

// -------------------------------------------------------------------

// ScannAssets

// repeated .research_scann.ScannAsset assets = 1;
inline int ScannAssets::_internal_assets_size() const {
  return _internal_assets().size();
}
inline int ScannAssets::assets_size() const {
  return _internal_assets_size();
}
inline void ScannAssets::clear_assets() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.assets_.Clear();
}
inline ::research_scann::ScannAsset* ScannAssets::mutable_assets(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:research_scann.ScannAssets.assets)
  return _internal_mutable_assets()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>* ScannAssets::mutable_assets()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:research_scann.ScannAssets.assets)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_assets();
}
inline const ::research_scann::ScannAsset& ScannAssets::assets(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.ScannAssets.assets)
  return _internal_assets().Get(index);
}
inline ::research_scann::ScannAsset* ScannAssets::add_assets() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::research_scann::ScannAsset* _add = _internal_mutable_assets()->Add();
  // @@protoc_insertion_point(field_add:research_scann.ScannAssets.assets)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>& ScannAssets::assets() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:research_scann.ScannAssets.assets)
  return _internal_assets();
}
inline const ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>&
ScannAssets::_internal_assets() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.assets_;
}
inline ::google::protobuf::RepeatedPtrField<::research_scann::ScannAsset>*
ScannAssets::_internal_mutable_assets() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.assets_;
}

// optional bool trained_on_the_fly = 2 [default = true];
inline bool ScannAssets::has_trained_on_the_fly() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScannAssets::clear_trained_on_the_fly() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.trained_on_the_fly_ = true;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool ScannAssets::trained_on_the_fly() const {
  // @@protoc_insertion_point(field_get:research_scann.ScannAssets.trained_on_the_fly)
  return _internal_trained_on_the_fly();
}
inline void ScannAssets::set_trained_on_the_fly(bool value) {
  _internal_set_trained_on_the_fly(value);
  // @@protoc_insertion_point(field_set:research_scann.ScannAssets.trained_on_the_fly)
}
inline bool ScannAssets::_internal_trained_on_the_fly() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.trained_on_the_fly_;
}
inline void ScannAssets::_internal_set_trained_on_the_fly(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.trained_on_the_fly_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::research_scann::ScannAsset_AssetType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::research_scann::ScannAsset_AssetType>() {
  return ::research_scann::ScannAsset_AssetType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_scann_2fscann_5fops_2fscann_5fassets_2eproto_2epb_2eh
