// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/partitioning/linear_projection_tree.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto;
namespace research_scann {
class SerializedLinearProjectionTree;
struct SerializedLinearProjectionTreeDefaultTypeInternal;
extern SerializedLinearProjectionTreeDefaultTypeInternal _SerializedLinearProjectionTree_default_instance_;
class SerializedLinearProjectionTree_Node;
struct SerializedLinearProjectionTree_NodeDefaultTypeInternal;
extern SerializedLinearProjectionTree_NodeDefaultTypeInternal _SerializedLinearProjectionTree_Node_default_instance_;
class SerializedLinearProjectionTree_Node_LeafFields;
struct SerializedLinearProjectionTree_Node_LeafFieldsDefaultTypeInternal;
extern SerializedLinearProjectionTree_Node_LeafFieldsDefaultTypeInternal _SerializedLinearProjectionTree_Node_LeafFields_default_instance_;
class SerializedLinearProjectionTree_Node_NonLeafFields;
struct SerializedLinearProjectionTree_Node_NonLeafFieldsDefaultTypeInternal;
extern SerializedLinearProjectionTree_Node_NonLeafFieldsDefaultTypeInternal _SerializedLinearProjectionTree_Node_NonLeafFields_default_instance_;
}  // namespace research_scann
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace research_scann {

// ===================================================================


// -------------------------------------------------------------------

class SerializedLinearProjectionTree_Node_LeafFields final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.SerializedLinearProjectionTree.Node.LeafFields) */ {
 public:
  inline SerializedLinearProjectionTree_Node_LeafFields() : SerializedLinearProjectionTree_Node_LeafFields(nullptr) {}
  ~SerializedLinearProjectionTree_Node_LeafFields() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SerializedLinearProjectionTree_Node_LeafFields(::google::protobuf::internal::ConstantInitialized);

  inline SerializedLinearProjectionTree_Node_LeafFields(const SerializedLinearProjectionTree_Node_LeafFields& from)
      : SerializedLinearProjectionTree_Node_LeafFields(nullptr, from) {}
  SerializedLinearProjectionTree_Node_LeafFields(SerializedLinearProjectionTree_Node_LeafFields&& from) noexcept
    : SerializedLinearProjectionTree_Node_LeafFields() {
    *this = ::std::move(from);
  }

  inline SerializedLinearProjectionTree_Node_LeafFields& operator=(const SerializedLinearProjectionTree_Node_LeafFields& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializedLinearProjectionTree_Node_LeafFields& operator=(SerializedLinearProjectionTree_Node_LeafFields&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializedLinearProjectionTree_Node_LeafFields& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializedLinearProjectionTree_Node_LeafFields* internal_default_instance() {
    return reinterpret_cast<const SerializedLinearProjectionTree_Node_LeafFields*>(
               &_SerializedLinearProjectionTree_Node_LeafFields_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SerializedLinearProjectionTree_Node_LeafFields& a, SerializedLinearProjectionTree_Node_LeafFields& b) {
    a.Swap(&b);
  }
  inline void Swap(SerializedLinearProjectionTree_Node_LeafFields* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializedLinearProjectionTree_Node_LeafFields* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializedLinearProjectionTree_Node_LeafFields* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SerializedLinearProjectionTree_Node_LeafFields>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializedLinearProjectionTree_Node_LeafFields& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SerializedLinearProjectionTree_Node_LeafFields& from) {
    SerializedLinearProjectionTree_Node_LeafFields::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SerializedLinearProjectionTree_Node_LeafFields* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.SerializedLinearProjectionTree.Node.LeafFields";
  }
  protected:
  explicit SerializedLinearProjectionTree_Node_LeafFields(::google::protobuf::Arena* arena);
  SerializedLinearProjectionTree_Node_LeafFields(::google::protobuf::Arena* arena, const SerializedLinearProjectionTree_Node_LeafFields& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeafNumberFieldNumber = 5,
  };
  // optional int32 leaf_number = 5;
  bool has_leaf_number() const;
  void clear_leaf_number() ;
  ::int32_t leaf_number() const;
  void set_leaf_number(::int32_t value);

  private:
  ::int32_t _internal_leaf_number() const;
  void _internal_set_leaf_number(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.SerializedLinearProjectionTree.Node.LeafFields)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t leaf_number_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto;
};// -------------------------------------------------------------------

class SerializedLinearProjectionTree_Node final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.SerializedLinearProjectionTree.Node) */ {
 public:
  inline SerializedLinearProjectionTree_Node() : SerializedLinearProjectionTree_Node(nullptr) {}
  ~SerializedLinearProjectionTree_Node() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SerializedLinearProjectionTree_Node(::google::protobuf::internal::ConstantInitialized);

  inline SerializedLinearProjectionTree_Node(const SerializedLinearProjectionTree_Node& from)
      : SerializedLinearProjectionTree_Node(nullptr, from) {}
  SerializedLinearProjectionTree_Node(SerializedLinearProjectionTree_Node&& from) noexcept
    : SerializedLinearProjectionTree_Node() {
    *this = ::std::move(from);
  }

  inline SerializedLinearProjectionTree_Node& operator=(const SerializedLinearProjectionTree_Node& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializedLinearProjectionTree_Node& operator=(SerializedLinearProjectionTree_Node&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializedLinearProjectionTree_Node& default_instance() {
    return *internal_default_instance();
  }
  enum LeafOrNonLeafCase {
    kNonLeaf = 1,
    kLeaf = 2,
    LEAF_OR_NON_LEAF_NOT_SET = 0,
  };

  static inline const SerializedLinearProjectionTree_Node* internal_default_instance() {
    return reinterpret_cast<const SerializedLinearProjectionTree_Node*>(
               &_SerializedLinearProjectionTree_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SerializedLinearProjectionTree_Node& a, SerializedLinearProjectionTree_Node& b) {
    a.Swap(&b);
  }
  inline void Swap(SerializedLinearProjectionTree_Node* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializedLinearProjectionTree_Node* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializedLinearProjectionTree_Node* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SerializedLinearProjectionTree_Node>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializedLinearProjectionTree_Node& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SerializedLinearProjectionTree_Node& from) {
    SerializedLinearProjectionTree_Node::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SerializedLinearProjectionTree_Node* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.SerializedLinearProjectionTree.Node";
  }
  protected:
  explicit SerializedLinearProjectionTree_Node(::google::protobuf::Arena* arena);
  SerializedLinearProjectionTree_Node(::google::protobuf::Arena* arena, const SerializedLinearProjectionTree_Node& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using NonLeafFields = SerializedLinearProjectionTree_Node_NonLeafFields;
  using LeafFields = SerializedLinearProjectionTree_Node_LeafFields;

  // accessors -------------------------------------------------------

  enum : int {
    kNonLeafFieldNumber = 1,
    kLeafFieldNumber = 2,
  };
  // .research_scann.SerializedLinearProjectionTree.Node.NonLeafFields non_leaf = 1;
  bool has_non_leaf() const;
  private:
  bool _internal_has_non_leaf() const;

  public:
  void clear_non_leaf() ;
  const ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields& non_leaf() const;
  PROTOBUF_NODISCARD ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* release_non_leaf();
  ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* mutable_non_leaf();
  void set_allocated_non_leaf(::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* value);
  void unsafe_arena_set_allocated_non_leaf(::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* value);
  ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* unsafe_arena_release_non_leaf();

  private:
  const ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields& _internal_non_leaf() const;
  ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* _internal_mutable_non_leaf();

  public:
  // .research_scann.SerializedLinearProjectionTree.Node.LeafFields leaf = 2;
  bool has_leaf() const;
  private:
  bool _internal_has_leaf() const;

  public:
  void clear_leaf() ;
  const ::research_scann::SerializedLinearProjectionTree_Node_LeafFields& leaf() const;
  PROTOBUF_NODISCARD ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* release_leaf();
  ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* mutable_leaf();
  void set_allocated_leaf(::research_scann::SerializedLinearProjectionTree_Node_LeafFields* value);
  void unsafe_arena_set_allocated_leaf(::research_scann::SerializedLinearProjectionTree_Node_LeafFields* value);
  ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* unsafe_arena_release_leaf();

  private:
  const ::research_scann::SerializedLinearProjectionTree_Node_LeafFields& _internal_leaf() const;
  ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* _internal_mutable_leaf();

  public:
  void clear_leaf_or_non_leaf();
  LeafOrNonLeafCase leaf_or_non_leaf_case() const;
  // @@protoc_insertion_point(class_scope:research_scann.SerializedLinearProjectionTree.Node)
 private:
  class _Internal;
  void set_has_non_leaf();
  void set_has_leaf();

  inline bool has_leaf_or_non_leaf() const;
  inline void clear_has_leaf_or_non_leaf();

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    union LeafOrNonLeafUnion {
      constexpr LeafOrNonLeafUnion() : _constinit_{} {}
        ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* non_leaf_;
      ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* leaf_;
    } leaf_or_non_leaf_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];

    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto;
};// -------------------------------------------------------------------

class SerializedLinearProjectionTree_Node_NonLeafFields final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields) */ {
 public:
  inline SerializedLinearProjectionTree_Node_NonLeafFields() : SerializedLinearProjectionTree_Node_NonLeafFields(nullptr) {}
  ~SerializedLinearProjectionTree_Node_NonLeafFields() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SerializedLinearProjectionTree_Node_NonLeafFields(::google::protobuf::internal::ConstantInitialized);

  inline SerializedLinearProjectionTree_Node_NonLeafFields(const SerializedLinearProjectionTree_Node_NonLeafFields& from)
      : SerializedLinearProjectionTree_Node_NonLeafFields(nullptr, from) {}
  SerializedLinearProjectionTree_Node_NonLeafFields(SerializedLinearProjectionTree_Node_NonLeafFields&& from) noexcept
    : SerializedLinearProjectionTree_Node_NonLeafFields() {
    *this = ::std::move(from);
  }

  inline SerializedLinearProjectionTree_Node_NonLeafFields& operator=(const SerializedLinearProjectionTree_Node_NonLeafFields& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializedLinearProjectionTree_Node_NonLeafFields& operator=(SerializedLinearProjectionTree_Node_NonLeafFields&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializedLinearProjectionTree_Node_NonLeafFields& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializedLinearProjectionTree_Node_NonLeafFields* internal_default_instance() {
    return reinterpret_cast<const SerializedLinearProjectionTree_Node_NonLeafFields*>(
               &_SerializedLinearProjectionTree_Node_NonLeafFields_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SerializedLinearProjectionTree_Node_NonLeafFields& a, SerializedLinearProjectionTree_Node_NonLeafFields& b) {
    a.Swap(&b);
  }
  inline void Swap(SerializedLinearProjectionTree_Node_NonLeafFields* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializedLinearProjectionTree_Node_NonLeafFields* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializedLinearProjectionTree_Node_NonLeafFields* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SerializedLinearProjectionTree_Node_NonLeafFields>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializedLinearProjectionTree_Node_NonLeafFields& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SerializedLinearProjectionTree_Node_NonLeafFields& from) {
    SerializedLinearProjectionTree_Node_NonLeafFields::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SerializedLinearProjectionTree_Node_NonLeafFields* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.SerializedLinearProjectionTree.Node.NonLeafFields";
  }
  protected:
  explicit SerializedLinearProjectionTree_Node_NonLeafFields(::google::protobuf::Arena* arena);
  SerializedLinearProjectionTree_Node_NonLeafFields(::google::protobuf::Arena* arena, const SerializedLinearProjectionTree_Node_NonLeafFields& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProjectionVectorFieldNumber = 1,
    kLeftFieldNumber = 3,
    kRightFieldNumber = 4,
    kThresholdFieldNumber = 2,
  };
  // repeated float projection_vector = 1;
  int projection_vector_size() const;
  private:
  int _internal_projection_vector_size() const;

  public:
  void clear_projection_vector() ;
  float projection_vector(int index) const;
  void set_projection_vector(int index, float value);
  void add_projection_vector(float value);
  const ::google::protobuf::RepeatedField<float>& projection_vector() const;
  ::google::protobuf::RepeatedField<float>* mutable_projection_vector();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_projection_vector() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_projection_vector();

  public:
  // optional .research_scann.SerializedLinearProjectionTree.Node left = 3;
  bool has_left() const;
  void clear_left() ;
  const ::research_scann::SerializedLinearProjectionTree_Node& left() const;
  PROTOBUF_NODISCARD ::research_scann::SerializedLinearProjectionTree_Node* release_left();
  ::research_scann::SerializedLinearProjectionTree_Node* mutable_left();
  void set_allocated_left(::research_scann::SerializedLinearProjectionTree_Node* value);
  void unsafe_arena_set_allocated_left(::research_scann::SerializedLinearProjectionTree_Node* value);
  ::research_scann::SerializedLinearProjectionTree_Node* unsafe_arena_release_left();

  private:
  const ::research_scann::SerializedLinearProjectionTree_Node& _internal_left() const;
  ::research_scann::SerializedLinearProjectionTree_Node* _internal_mutable_left();

  public:
  // optional .research_scann.SerializedLinearProjectionTree.Node right = 4;
  bool has_right() const;
  void clear_right() ;
  const ::research_scann::SerializedLinearProjectionTree_Node& right() const;
  PROTOBUF_NODISCARD ::research_scann::SerializedLinearProjectionTree_Node* release_right();
  ::research_scann::SerializedLinearProjectionTree_Node* mutable_right();
  void set_allocated_right(::research_scann::SerializedLinearProjectionTree_Node* value);
  void unsafe_arena_set_allocated_right(::research_scann::SerializedLinearProjectionTree_Node* value);
  ::research_scann::SerializedLinearProjectionTree_Node* unsafe_arena_release_right();

  private:
  const ::research_scann::SerializedLinearProjectionTree_Node& _internal_right() const;
  ::research_scann::SerializedLinearProjectionTree_Node* _internal_mutable_right();

  public:
  // optional float threshold = 2;
  bool has_threshold() const;
  void clear_threshold() ;
  float threshold() const;
  void set_threshold(float value);

  private:
  float _internal_threshold() const;
  void _internal_set_threshold(float value);

  public:
  // @@protoc_insertion_point(class_scope:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> projection_vector_;
    ::research_scann::SerializedLinearProjectionTree_Node* left_;
    ::research_scann::SerializedLinearProjectionTree_Node* right_;
    float threshold_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto;
};// -------------------------------------------------------------------

class SerializedLinearProjectionTree final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:research_scann.SerializedLinearProjectionTree) */ {
 public:
  inline SerializedLinearProjectionTree() : SerializedLinearProjectionTree(nullptr) {}
  ~SerializedLinearProjectionTree() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SerializedLinearProjectionTree(::google::protobuf::internal::ConstantInitialized);

  inline SerializedLinearProjectionTree(const SerializedLinearProjectionTree& from)
      : SerializedLinearProjectionTree(nullptr, from) {}
  SerializedLinearProjectionTree(SerializedLinearProjectionTree&& from) noexcept
    : SerializedLinearProjectionTree() {
    *this = ::std::move(from);
  }

  inline SerializedLinearProjectionTree& operator=(const SerializedLinearProjectionTree& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializedLinearProjectionTree& operator=(SerializedLinearProjectionTree&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializedLinearProjectionTree& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializedLinearProjectionTree* internal_default_instance() {
    return reinterpret_cast<const SerializedLinearProjectionTree*>(
               &_SerializedLinearProjectionTree_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SerializedLinearProjectionTree& a, SerializedLinearProjectionTree& b) {
    a.Swap(&b);
  }
  inline void Swap(SerializedLinearProjectionTree* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializedLinearProjectionTree* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializedLinearProjectionTree* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SerializedLinearProjectionTree>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializedLinearProjectionTree& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SerializedLinearProjectionTree& from) {
    SerializedLinearProjectionTree::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SerializedLinearProjectionTree* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "research_scann.SerializedLinearProjectionTree";
  }
  protected:
  explicit SerializedLinearProjectionTree(::google::protobuf::Arena* arena);
  SerializedLinearProjectionTree(::google::protobuf::Arena* arena, const SerializedLinearProjectionTree& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using Node = SerializedLinearProjectionTree_Node;

  // accessors -------------------------------------------------------

  enum : int {
    kRootFieldNumber = 1,
  };
  // optional .research_scann.SerializedLinearProjectionTree.Node root = 1;
  bool has_root() const;
  void clear_root() ;
  const ::research_scann::SerializedLinearProjectionTree_Node& root() const;
  PROTOBUF_NODISCARD ::research_scann::SerializedLinearProjectionTree_Node* release_root();
  ::research_scann::SerializedLinearProjectionTree_Node* mutable_root();
  void set_allocated_root(::research_scann::SerializedLinearProjectionTree_Node* value);
  void unsafe_arena_set_allocated_root(::research_scann::SerializedLinearProjectionTree_Node* value);
  ::research_scann::SerializedLinearProjectionTree_Node* unsafe_arena_release_root();

  private:
  const ::research_scann::SerializedLinearProjectionTree_Node& _internal_root() const;
  ::research_scann::SerializedLinearProjectionTree_Node* _internal_mutable_root();

  public:
  // @@protoc_insertion_point(class_scope:research_scann.SerializedLinearProjectionTree)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::research_scann::SerializedLinearProjectionTree_Node* root_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializedLinearProjectionTree_Node_NonLeafFields

// repeated float projection_vector = 1;
inline int SerializedLinearProjectionTree_Node_NonLeafFields::_internal_projection_vector_size() const {
  return _internal_projection_vector().size();
}
inline int SerializedLinearProjectionTree_Node_NonLeafFields::projection_vector_size() const {
  return _internal_projection_vector_size();
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::clear_projection_vector() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.projection_vector_.Clear();
}
inline float SerializedLinearProjectionTree_Node_NonLeafFields::projection_vector(int index) const {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.projection_vector)
  return _internal_projection_vector().Get(index);
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::set_projection_vector(int index, float value) {
  _internal_mutable_projection_vector()->Set(index, value);
  // @@protoc_insertion_point(field_set:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.projection_vector)
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::add_projection_vector(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_projection_vector()->Add(value);
  // @@protoc_insertion_point(field_add:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.projection_vector)
}
inline const ::google::protobuf::RepeatedField<float>& SerializedLinearProjectionTree_Node_NonLeafFields::projection_vector() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.projection_vector)
  return _internal_projection_vector();
}
inline ::google::protobuf::RepeatedField<float>* SerializedLinearProjectionTree_Node_NonLeafFields::mutable_projection_vector()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.projection_vector)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_projection_vector();
}
inline const ::google::protobuf::RepeatedField<float>& SerializedLinearProjectionTree_Node_NonLeafFields::_internal_projection_vector()
    const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.projection_vector_;
}
inline ::google::protobuf::RepeatedField<float>* SerializedLinearProjectionTree_Node_NonLeafFields::_internal_mutable_projection_vector() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.projection_vector_;
}

// optional float threshold = 2;
inline bool SerializedLinearProjectionTree_Node_NonLeafFields::has_threshold() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::clear_threshold() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.threshold_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float SerializedLinearProjectionTree_Node_NonLeafFields::threshold() const {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.threshold)
  return _internal_threshold();
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::set_threshold(float value) {
  _internal_set_threshold(value);
  // @@protoc_insertion_point(field_set:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.threshold)
}
inline float SerializedLinearProjectionTree_Node_NonLeafFields::_internal_threshold() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.threshold_;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::_internal_set_threshold(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.threshold_ = value;
}

// optional .research_scann.SerializedLinearProjectionTree.Node left = 3;
inline bool SerializedLinearProjectionTree_Node_NonLeafFields::has_left() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.left_ != nullptr);
  return value;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::clear_left() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.left_ != nullptr) _impl_.left_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree_Node_NonLeafFields::_internal_left() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::research_scann::SerializedLinearProjectionTree_Node* p = _impl_.left_;
  return p != nullptr ? *p : reinterpret_cast<const ::research_scann::SerializedLinearProjectionTree_Node&>(::research_scann::_SerializedLinearProjectionTree_Node_default_instance_);
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree_Node_NonLeafFields::left() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.left)
  return _internal_left();
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::unsafe_arena_set_allocated_left(::research_scann::SerializedLinearProjectionTree_Node* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.left_);
  }
  _impl_.left_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.left)
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::release_left() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::SerializedLinearProjectionTree_Node* released = _impl_.left_;
  _impl_.left_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::unsafe_arena_release_left() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.left)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::SerializedLinearProjectionTree_Node* temp = _impl_.left_;
  _impl_.left_ = nullptr;
  return temp;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::_internal_mutable_left() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.left_ == nullptr) {
    auto* p = CreateMaybeMessage<::research_scann::SerializedLinearProjectionTree_Node>(GetArena());
    _impl_.left_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(p);
  }
  return _impl_.left_;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::mutable_left() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::SerializedLinearProjectionTree_Node* _msg = _internal_mutable_left();
  // @@protoc_insertion_point(field_mutable:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.left)
  return _msg;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::set_allocated_left(::research_scann::SerializedLinearProjectionTree_Node* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(_impl_.left_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.left_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  // @@protoc_insertion_point(field_set_allocated:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.left)
}

// optional .research_scann.SerializedLinearProjectionTree.Node right = 4;
inline bool SerializedLinearProjectionTree_Node_NonLeafFields::has_right() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.right_ != nullptr);
  return value;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::clear_right() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.right_ != nullptr) _impl_.right_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree_Node_NonLeafFields::_internal_right() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::research_scann::SerializedLinearProjectionTree_Node* p = _impl_.right_;
  return p != nullptr ? *p : reinterpret_cast<const ::research_scann::SerializedLinearProjectionTree_Node&>(::research_scann::_SerializedLinearProjectionTree_Node_default_instance_);
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree_Node_NonLeafFields::right() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.right)
  return _internal_right();
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::unsafe_arena_set_allocated_right(::research_scann::SerializedLinearProjectionTree_Node* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.right_);
  }
  _impl_.right_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.right)
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::release_right() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::research_scann::SerializedLinearProjectionTree_Node* released = _impl_.right_;
  _impl_.right_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::unsafe_arena_release_right() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.right)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::research_scann::SerializedLinearProjectionTree_Node* temp = _impl_.right_;
  _impl_.right_ = nullptr;
  return temp;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::_internal_mutable_right() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.right_ == nullptr) {
    auto* p = CreateMaybeMessage<::research_scann::SerializedLinearProjectionTree_Node>(GetArena());
    _impl_.right_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(p);
  }
  return _impl_.right_;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree_Node_NonLeafFields::mutable_right() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::SerializedLinearProjectionTree_Node* _msg = _internal_mutable_right();
  // @@protoc_insertion_point(field_mutable:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.right)
  return _msg;
}
inline void SerializedLinearProjectionTree_Node_NonLeafFields::set_allocated_right(::research_scann::SerializedLinearProjectionTree_Node* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(_impl_.right_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.right_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  // @@protoc_insertion_point(field_set_allocated:research_scann.SerializedLinearProjectionTree.Node.NonLeafFields.right)
}

// -------------------------------------------------------------------

// SerializedLinearProjectionTree_Node_LeafFields

// optional int32 leaf_number = 5;
inline bool SerializedLinearProjectionTree_Node_LeafFields::has_leaf_number() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SerializedLinearProjectionTree_Node_LeafFields::clear_leaf_number() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.leaf_number_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t SerializedLinearProjectionTree_Node_LeafFields::leaf_number() const {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.LeafFields.leaf_number)
  return _internal_leaf_number();
}
inline void SerializedLinearProjectionTree_Node_LeafFields::set_leaf_number(::int32_t value) {
  _internal_set_leaf_number(value);
  // @@protoc_insertion_point(field_set:research_scann.SerializedLinearProjectionTree.Node.LeafFields.leaf_number)
}
inline ::int32_t SerializedLinearProjectionTree_Node_LeafFields::_internal_leaf_number() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.leaf_number_;
}
inline void SerializedLinearProjectionTree_Node_LeafFields::_internal_set_leaf_number(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.leaf_number_ = value;
}

// -------------------------------------------------------------------

// SerializedLinearProjectionTree_Node

// .research_scann.SerializedLinearProjectionTree.Node.NonLeafFields non_leaf = 1;
inline bool SerializedLinearProjectionTree_Node::has_non_leaf() const {
  return leaf_or_non_leaf_case() == kNonLeaf;
}
inline bool SerializedLinearProjectionTree_Node::_internal_has_non_leaf() const {
  return leaf_or_non_leaf_case() == kNonLeaf;
}
inline void SerializedLinearProjectionTree_Node::set_has_non_leaf() {
  _impl_._oneof_case_[0] = kNonLeaf;
}
inline void SerializedLinearProjectionTree_Node::clear_non_leaf() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (leaf_or_non_leaf_case() == kNonLeaf) {
    if (GetArena() == nullptr) {
      delete _impl_.leaf_or_non_leaf_.non_leaf_;
    }
    clear_has_leaf_or_non_leaf();
  }
}
inline ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* SerializedLinearProjectionTree_Node::release_non_leaf() {
  // @@protoc_insertion_point(field_release:research_scann.SerializedLinearProjectionTree.Node.non_leaf)
  if (leaf_or_non_leaf_case() == kNonLeaf) {
    clear_has_leaf_or_non_leaf();
    auto* temp = _impl_.leaf_or_non_leaf_.non_leaf_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.leaf_or_non_leaf_.non_leaf_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields& SerializedLinearProjectionTree_Node::_internal_non_leaf() const {
  return leaf_or_non_leaf_case() == kNonLeaf ? *_impl_.leaf_or_non_leaf_.non_leaf_ : reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields&>(::research_scann::_SerializedLinearProjectionTree_Node_NonLeafFields_default_instance_);
}
inline const ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields& SerializedLinearProjectionTree_Node::non_leaf() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.non_leaf)
  return _internal_non_leaf();
}
inline ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* SerializedLinearProjectionTree_Node::unsafe_arena_release_non_leaf() {
  // @@protoc_insertion_point(field_unsafe_arena_release:research_scann.SerializedLinearProjectionTree.Node.non_leaf)
  if (leaf_or_non_leaf_case() == kNonLeaf) {
    clear_has_leaf_or_non_leaf();
    auto* temp = _impl_.leaf_or_non_leaf_.non_leaf_;
    _impl_.leaf_or_non_leaf_.non_leaf_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SerializedLinearProjectionTree_Node::unsafe_arena_set_allocated_non_leaf(::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_leaf_or_non_leaf();
  if (value) {
    set_has_non_leaf();
    _impl_.leaf_or_non_leaf_.non_leaf_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.SerializedLinearProjectionTree.Node.non_leaf)
}
inline ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* SerializedLinearProjectionTree_Node::_internal_mutable_non_leaf() {
  if (leaf_or_non_leaf_case() != kNonLeaf) {
    clear_leaf_or_non_leaf();
    set_has_non_leaf();
    _impl_.leaf_or_non_leaf_.non_leaf_ = CreateMaybeMessage<::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields>(GetArena());
  }
  return _impl_.leaf_or_non_leaf_.non_leaf_;
}
inline ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* SerializedLinearProjectionTree_Node::mutable_non_leaf() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::SerializedLinearProjectionTree_Node_NonLeafFields* _msg = _internal_mutable_non_leaf();
  // @@protoc_insertion_point(field_mutable:research_scann.SerializedLinearProjectionTree.Node.non_leaf)
  return _msg;
}

// .research_scann.SerializedLinearProjectionTree.Node.LeafFields leaf = 2;
inline bool SerializedLinearProjectionTree_Node::has_leaf() const {
  return leaf_or_non_leaf_case() == kLeaf;
}
inline bool SerializedLinearProjectionTree_Node::_internal_has_leaf() const {
  return leaf_or_non_leaf_case() == kLeaf;
}
inline void SerializedLinearProjectionTree_Node::set_has_leaf() {
  _impl_._oneof_case_[0] = kLeaf;
}
inline void SerializedLinearProjectionTree_Node::clear_leaf() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (leaf_or_non_leaf_case() == kLeaf) {
    if (GetArena() == nullptr) {
      delete _impl_.leaf_or_non_leaf_.leaf_;
    }
    clear_has_leaf_or_non_leaf();
  }
}
inline ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* SerializedLinearProjectionTree_Node::release_leaf() {
  // @@protoc_insertion_point(field_release:research_scann.SerializedLinearProjectionTree.Node.leaf)
  if (leaf_or_non_leaf_case() == kLeaf) {
    clear_has_leaf_or_non_leaf();
    auto* temp = _impl_.leaf_or_non_leaf_.leaf_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.leaf_or_non_leaf_.leaf_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::research_scann::SerializedLinearProjectionTree_Node_LeafFields& SerializedLinearProjectionTree_Node::_internal_leaf() const {
  return leaf_or_non_leaf_case() == kLeaf ? *_impl_.leaf_or_non_leaf_.leaf_ : reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node_LeafFields&>(::research_scann::_SerializedLinearProjectionTree_Node_LeafFields_default_instance_);
}
inline const ::research_scann::SerializedLinearProjectionTree_Node_LeafFields& SerializedLinearProjectionTree_Node::leaf() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.Node.leaf)
  return _internal_leaf();
}
inline ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* SerializedLinearProjectionTree_Node::unsafe_arena_release_leaf() {
  // @@protoc_insertion_point(field_unsafe_arena_release:research_scann.SerializedLinearProjectionTree.Node.leaf)
  if (leaf_or_non_leaf_case() == kLeaf) {
    clear_has_leaf_or_non_leaf();
    auto* temp = _impl_.leaf_or_non_leaf_.leaf_;
    _impl_.leaf_or_non_leaf_.leaf_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SerializedLinearProjectionTree_Node::unsafe_arena_set_allocated_leaf(::research_scann::SerializedLinearProjectionTree_Node_LeafFields* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_leaf_or_non_leaf();
  if (value) {
    set_has_leaf();
    _impl_.leaf_or_non_leaf_.leaf_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.SerializedLinearProjectionTree.Node.leaf)
}
inline ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* SerializedLinearProjectionTree_Node::_internal_mutable_leaf() {
  if (leaf_or_non_leaf_case() != kLeaf) {
    clear_leaf_or_non_leaf();
    set_has_leaf();
    _impl_.leaf_or_non_leaf_.leaf_ = CreateMaybeMessage<::research_scann::SerializedLinearProjectionTree_Node_LeafFields>(GetArena());
  }
  return _impl_.leaf_or_non_leaf_.leaf_;
}
inline ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* SerializedLinearProjectionTree_Node::mutable_leaf() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::SerializedLinearProjectionTree_Node_LeafFields* _msg = _internal_mutable_leaf();
  // @@protoc_insertion_point(field_mutable:research_scann.SerializedLinearProjectionTree.Node.leaf)
  return _msg;
}

inline bool SerializedLinearProjectionTree_Node::has_leaf_or_non_leaf() const {
  return leaf_or_non_leaf_case() != LEAF_OR_NON_LEAF_NOT_SET;
}
inline void SerializedLinearProjectionTree_Node::clear_has_leaf_or_non_leaf() {
  _impl_._oneof_case_[0] = LEAF_OR_NON_LEAF_NOT_SET;
}
inline SerializedLinearProjectionTree_Node::LeafOrNonLeafCase SerializedLinearProjectionTree_Node::leaf_or_non_leaf_case() const {
  return SerializedLinearProjectionTree_Node::LeafOrNonLeafCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// SerializedLinearProjectionTree

// optional .research_scann.SerializedLinearProjectionTree.Node root = 1;
inline bool SerializedLinearProjectionTree::has_root() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.root_ != nullptr);
  return value;
}
inline void SerializedLinearProjectionTree::clear_root() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.root_ != nullptr) _impl_.root_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree::_internal_root() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::research_scann::SerializedLinearProjectionTree_Node* p = _impl_.root_;
  return p != nullptr ? *p : reinterpret_cast<const ::research_scann::SerializedLinearProjectionTree_Node&>(::research_scann::_SerializedLinearProjectionTree_Node_default_instance_);
}
inline const ::research_scann::SerializedLinearProjectionTree_Node& SerializedLinearProjectionTree::root() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:research_scann.SerializedLinearProjectionTree.root)
  return _internal_root();
}
inline void SerializedLinearProjectionTree::unsafe_arena_set_allocated_root(::research_scann::SerializedLinearProjectionTree_Node* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.root_);
  }
  _impl_.root_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:research_scann.SerializedLinearProjectionTree.root)
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree::release_root() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::SerializedLinearProjectionTree_Node* released = _impl_.root_;
  _impl_.root_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree::unsafe_arena_release_root() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:research_scann.SerializedLinearProjectionTree.root)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::research_scann::SerializedLinearProjectionTree_Node* temp = _impl_.root_;
  _impl_.root_ = nullptr;
  return temp;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree::_internal_mutable_root() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.root_ == nullptr) {
    auto* p = CreateMaybeMessage<::research_scann::SerializedLinearProjectionTree_Node>(GetArena());
    _impl_.root_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(p);
  }
  return _impl_.root_;
}
inline ::research_scann::SerializedLinearProjectionTree_Node* SerializedLinearProjectionTree::mutable_root() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::research_scann::SerializedLinearProjectionTree_Node* _msg = _internal_mutable_root();
  // @@protoc_insertion_point(field_mutable:research_scann.SerializedLinearProjectionTree.root)
  return _msg;
}
inline void SerializedLinearProjectionTree::set_allocated_root(::research_scann::SerializedLinearProjectionTree_Node* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(_impl_.root_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.root_ = reinterpret_cast<::research_scann::SerializedLinearProjectionTree_Node*>(value);
  // @@protoc_insertion_point(field_set_allocated:research_scann.SerializedLinearProjectionTree.root)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_scann_2fpartitioning_2flinear_5fprojection_5ftree_2eproto_2epb_2eh
